import { describe, test, expect } from 'vitest';
import { PackError, BriefGenerationError, BriefNotFoundError, ReflectionGenerationError, GoalNotFoundError, GoalValidationError, GoalHierarchyError, DecisionNotFoundError, DecisionValidationError, ConstraintNotFoundError, ConstraintAnalysisError, ValueAssessmentError, RecommendationComposeError, RecommendationChainError, RecommendationNotFoundError, KnowledgeNodeError, KnowledgeEdgeError, ConversationInterpretError, HabitInsightError, PriorityCalculationError, DashboardGenerationError, FirstIntelligenceError, PackDisposedError, PackStateError, ContractNotAvailableError } from '../../core/personal-intelligence/errors.js';

describe('Errors Deep', () => {
test('PackError has code PACK_ERROR', () => { const e = new PackError('m'); expect(e.code).toBe('PACK_ERROR'); });
test('PackError default details is empty', () => { const e = new PackError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('PackError accepts details', () => { const e = new PackError('m', 'CODE', { k: 'v' }); expect(e.details).toEqual({k:'v'}); });
test('PackError is instanceof Error', () => { expect(new PackError('m')).toBeInstanceOf(Error); });
test('PackError is instanceof PackError', () => { expect(new PackError('m')).toBeInstanceOf(PackError); });
test('PackError has stack trace', () => { const e = new PackError('m'); expect(e.stack).toBeDefined(); });
test('PackError can be thrown and caught', () => { expect(() => { throw new PackError('test'); }).toThrow(PackError); });
test('PackError message matches', () => { expect(new PackError('hello').message).toBe('hello'); });
test('PackError accepts custom code', () => { const e = new PackError('m','CUSTOM'); expect(e.code).toBe('CUSTOM'); });
test('PackError name is PackError', () => { const e = new PackError('m'); expect(e.name).toBe('PackError'); });
test('BriefGenerationError has code BRIEF_GENERATION_ERROR', () => { const e = new BriefGenerationError('m'); expect(e.code).toBe('BRIEF_GENERATION_ERROR'); });
test('BriefGenerationError default details is empty', () => { const e = new BriefGenerationError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('BriefGenerationError has name', () => { const e = new BriefGenerationError('m'); expect(e.name).toBe('BriefGenerationError'); });
test('BriefGenerationError is instanceof Error', () => { expect(new BriefGenerationError('m')).toBeInstanceOf(Error); });
test('BriefGenerationError is instanceof PackError', () => { expect(new BriefGenerationError('m')).toBeInstanceOf(PackError); });
test('BriefGenerationError has stack trace', () => { const e = new BriefGenerationError('m'); expect(e.stack).toBeDefined(); });
test('BriefGenerationError can be thrown and caught', () => { expect(() => { throw new BriefGenerationError('test'); }).toThrow(BriefGenerationError); });
test('BriefGenerationError message matches', () => { expect(new BriefGenerationError('hello').message).toBe('hello'); });
test('BriefGenerationError default reason', () => { const e = new BriefGenerationError(); expect(e.message).toBe('Daily brief generation failed'); });
test('BriefNotFoundError has code BRIEF_NOT_FOUND', () => { const e = new BriefNotFoundError('m'); expect(e.code).toBe('BRIEF_NOT_FOUND'); });
test('BriefNotFoundError default details is empty', () => { const e = new BriefNotFoundError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('BriefNotFoundError has briefId', () => { const e = new BriefNotFoundError('b1'); expect(e.briefId).toBe('b1'); });
test('BriefNotFoundError is instanceof Error', () => { expect(new BriefNotFoundError('m')).toBeInstanceOf(Error); });
test('BriefNotFoundError is instanceof PackError', () => { expect(new BriefNotFoundError('m')).toBeInstanceOf(PackError); });
test('BriefNotFoundError has stack trace', () => { const e = new BriefNotFoundError('m'); expect(e.stack).toBeDefined(); });
test('BriefNotFoundError can be thrown and caught', () => { expect(() => { throw new BriefNotFoundError('test'); }).toThrow(BriefNotFoundError); });
test('BriefNotFoundError message contains id', () => { expect(new BriefNotFoundError('myid').message).toContain('myid'); });
test('ReflectionGenerationError has code REFLECTION_GENERATION_ERROR', () => { const e = new ReflectionGenerationError('m'); expect(e.code).toBe('REFLECTION_GENERATION_ERROR'); });
test('ReflectionGenerationError default details is empty', () => { const e = new ReflectionGenerationError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('ReflectionGenerationError has name', () => { const e = new ReflectionGenerationError('m'); expect(e.name).toBe('ReflectionGenerationError'); });
test('ReflectionGenerationError is instanceof Error', () => { expect(new ReflectionGenerationError('m')).toBeInstanceOf(Error); });
test('ReflectionGenerationError is instanceof PackError', () => { expect(new ReflectionGenerationError('m')).toBeInstanceOf(PackError); });
test('ReflectionGenerationError has stack trace', () => { const e = new ReflectionGenerationError('m'); expect(e.stack).toBeDefined(); });
test('ReflectionGenerationError can be thrown and caught', () => { expect(() => { throw new ReflectionGenerationError('test'); }).toThrow(ReflectionGenerationError); });
test('ReflectionGenerationError message matches', () => { expect(new ReflectionGenerationError('hello').message).toBe('hello'); });
test('ReflectionGenerationError default reason', () => { const e = new ReflectionGenerationError(); expect(e.message).toBe('Reflection generation failed'); });
test('GoalNotFoundError has code GOAL_NOT_FOUND', () => { const e = new GoalNotFoundError('m'); expect(e.code).toBe('GOAL_NOT_FOUND'); });
test('GoalNotFoundError default details is empty', () => { const e = new GoalNotFoundError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('GoalNotFoundError has goalId', () => { const e = new GoalNotFoundError('g1'); expect(e.goalId).toBe('g1'); });
test('GoalNotFoundError is instanceof Error', () => { expect(new GoalNotFoundError('m')).toBeInstanceOf(Error); });
test('GoalNotFoundError is instanceof PackError', () => { expect(new GoalNotFoundError('m')).toBeInstanceOf(PackError); });
test('GoalNotFoundError has stack trace', () => { const e = new GoalNotFoundError('m'); expect(e.stack).toBeDefined(); });
test('GoalNotFoundError can be thrown and caught', () => { expect(() => { throw new GoalNotFoundError('test'); }).toThrow(GoalNotFoundError); });
test('GoalNotFoundError message contains id', () => { expect(new GoalNotFoundError('mygoal').message).toContain('mygoal'); });
test('GoalValidationError has code GOAL_VALIDATION_ERROR', () => { const e = new GoalValidationError(['v1']); expect(e.code).toBe('GOAL_VALIDATION_ERROR'); });
test('GoalValidationError default details is empty', () => { const e = new GoalValidationError(['v1']); expect(Object.keys(e.details).length).toBe(0); });
test('GoalValidationError has violations', () => { const e = new GoalValidationError(['a','b']); expect(e.violations.length).toBe(2); expect(e.violations[0]).toBe('a'); });
test('GoalValidationError is instanceof Error', () => { expect(new GoalValidationError(['v'])).toBeInstanceOf(Error); });
test('GoalValidationError is instanceof PackError', () => { expect(new GoalValidationError(['v'])).toBeInstanceOf(PackError); });
test('GoalValidationError has stack trace', () => { const e = new GoalValidationError(['v']); expect(e.stack).toBeDefined(); });
test('GoalValidationError can be thrown and caught', () => { expect(() => { throw new GoalValidationError(['test']); }).toThrow(GoalValidationError); });
test('GoalValidationError message contains violation', () => { expect(new GoalValidationError(['title missing']).message).toContain('title missing'); });
test('GoalHierarchyError has code GOAL_HIERARCHY_CYCLE', () => { const e = new GoalHierarchyError('g1','p1'); expect(e.code).toBe('GOAL_HIERARCHY_CYCLE'); });
test('GoalHierarchyError default details is empty', () => { const e = new GoalHierarchyError('g1','p1'); expect(Object.keys(e.details).length).toBe(0); });
test('GoalHierarchyError has goalId and parentId', () => { const e = new GoalHierarchyError('g1','p1'); expect(e.goalId).toBe('g1'); expect(e.parentId).toBe('p1'); });
test('GoalHierarchyError is instanceof Error', () => { expect(new GoalHierarchyError('g','p')).toBeInstanceOf(Error); });
test('GoalHierarchyError is instanceof PackError', () => { expect(new GoalHierarchyError('g','p')).toBeInstanceOf(PackError); });
test('GoalHierarchyError has stack trace', () => { const e = new GoalHierarchyError('g','p'); expect(e.stack).toBeDefined(); });
test('GoalHierarchyError can be thrown and caught', () => { expect(() => { throw new GoalHierarchyError('g','p'); }).toThrow(GoalHierarchyError); });
test('GoalHierarchyError message contains ids', () => { const e = new GoalHierarchyError('child','parent'); expect(e.message).toContain('child'); expect(e.message).toContain('parent'); });
test('DecisionNotFoundError has code DECISION_NOT_FOUND', () => { const e = new DecisionNotFoundError('m'); expect(e.code).toBe('DECISION_NOT_FOUND'); });
test('DecisionNotFoundError default details is empty', () => { const e = new DecisionNotFoundError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('DecisionNotFoundError has decisionId', () => { const e = new DecisionNotFoundError('d1'); expect(e.decisionId).toBe('d1'); });
test('DecisionNotFoundError is instanceof Error', () => { expect(new DecisionNotFoundError('m')).toBeInstanceOf(Error); });
test('DecisionNotFoundError is instanceof PackError', () => { expect(new DecisionNotFoundError('m')).toBeInstanceOf(PackError); });
test('DecisionNotFoundError has stack trace', () => { const e = new DecisionNotFoundError('m'); expect(e.stack).toBeDefined(); });
test('DecisionNotFoundError can be thrown and caught', () => { expect(() => { throw new DecisionNotFoundError('test'); }).toThrow(DecisionNotFoundError); });
test('DecisionNotFoundError message contains id', () => { expect(new DecisionNotFoundError('mydec').message).toContain('mydec'); });
test('DecisionValidationError has code DECISION_VALIDATION_ERROR', () => { const e = new DecisionValidationError(['v1']); expect(e.code).toBe('DECISION_VALIDATION_ERROR'); });
test('DecisionValidationError default details is empty', () => { const e = new DecisionValidationError(['v1']); expect(Object.keys(e.details).length).toBe(0); });
test('DecisionValidationError has violations', () => { const e = new DecisionValidationError(['a','b']); expect(e.violations.length).toBe(2); });
test('DecisionValidationError is instanceof Error', () => { expect(new DecisionValidationError(['v'])).toBeInstanceOf(Error); });
test('DecisionValidationError is instanceof PackError', () => { expect(new DecisionValidationError(['v'])).toBeInstanceOf(PackError); });
test('DecisionValidationError has stack trace', () => { const e = new DecisionValidationError(['v']); expect(e.stack).toBeDefined(); });
test('DecisionValidationError can be thrown and caught', () => { expect(() => { throw new DecisionValidationError(['test']); }).toThrow(DecisionValidationError); });
test('DecisionValidationError message contains violation', () => { expect(new DecisionValidationError(['title missing']).message).toContain('title missing'); });
test('ConstraintNotFoundError has code CONSTRAINT_NOT_FOUND', () => { const e = new ConstraintNotFoundError('m'); expect(e.code).toBe('CONSTRAINT_NOT_FOUND'); });
test('ConstraintNotFoundError default details is empty', () => { const e = new ConstraintNotFoundError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('ConstraintNotFoundError has constraintId', () => { const e = new ConstraintNotFoundError('c1'); expect(e.constraintId).toBe('c1'); });
test('ConstraintNotFoundError is instanceof Error', () => { expect(new ConstraintNotFoundError('m')).toBeInstanceOf(Error); });
test('ConstraintNotFoundError is instanceof PackError', () => { expect(new ConstraintNotFoundError('m')).toBeInstanceOf(PackError); });
test('ConstraintNotFoundError has stack trace', () => { const e = new ConstraintNotFoundError('m'); expect(e.stack).toBeDefined(); });
test('ConstraintNotFoundError can be thrown and caught', () => { expect(() => { throw new ConstraintNotFoundError('test'); }).toThrow(ConstraintNotFoundError); });
test('ConstraintNotFoundError message contains id', () => { expect(new ConstraintNotFoundError('myc').message).toContain('myc'); });
test('ConstraintAnalysisError has code CONSTRAINT_ANALYSIS_ERROR', () => { const e = new ConstraintAnalysisError('m'); expect(e.code).toBe('CONSTRAINT_ANALYSIS_ERROR'); });
test('ConstraintAnalysisError default details is empty', () => { const e = new ConstraintAnalysisError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('ConstraintAnalysisError has name', () => { const e = new ConstraintAnalysisError('m'); expect(e.name).toBe('ConstraintAnalysisError'); });
test('ConstraintAnalysisError is instanceof Error', () => { expect(new ConstraintAnalysisError('m')).toBeInstanceOf(Error); });
test('ConstraintAnalysisError is instanceof PackError', () => { expect(new ConstraintAnalysisError('m')).toBeInstanceOf(PackError); });
test('ConstraintAnalysisError has stack trace', () => { const e = new ConstraintAnalysisError('m'); expect(e.stack).toBeDefined(); });
test('ConstraintAnalysisError can be thrown and caught', () => { expect(() => { throw new ConstraintAnalysisError('test'); }).toThrow(ConstraintAnalysisError); });
test('ConstraintAnalysisError message matches', () => { expect(new ConstraintAnalysisError('hello').message).toBe('hello'); });
test('ConstraintAnalysisError default reason', () => { const e = new ConstraintAnalysisError(); expect(e.message).toBe('Constraint analysis failed'); });
test('ValueAssessmentError has code VALUE_ASSESSMENT_ERROR', () => { const e = new ValueAssessmentError('m'); expect(e.code).toBe('VALUE_ASSESSMENT_ERROR'); });
test('ValueAssessmentError default details is empty', () => { const e = new ValueAssessmentError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('ValueAssessmentError has name', () => { const e = new ValueAssessmentError('m'); expect(e.name).toBe('ValueAssessmentError'); });
test('ValueAssessmentError is instanceof Error', () => { expect(new ValueAssessmentError('m')).toBeInstanceOf(Error); });
test('ValueAssessmentError is instanceof PackError', () => { expect(new ValueAssessmentError('m')).toBeInstanceOf(PackError); });
test('ValueAssessmentError has stack trace', () => { const e = new ValueAssessmentError('m'); expect(e.stack).toBeDefined(); });
test('ValueAssessmentError can be thrown and caught', () => { expect(() => { throw new ValueAssessmentError('test'); }).toThrow(ValueAssessmentError); });
test('ValueAssessmentError message matches', () => { expect(new ValueAssessmentError('hello').message).toBe('hello'); });
test('ValueAssessmentError default reason', () => { const e = new ValueAssessmentError(); expect(e.message).toBe('Value assessment failed'); });
test('RecommendationComposeError has code RECOMMENDATION_COMPOSE_ERROR', () => { const e = new RecommendationComposeError('m'); expect(e.code).toBe('RECOMMENDATION_COMPOSE_ERROR'); });
test('RecommendationComposeError default details is empty', () => { const e = new RecommendationComposeError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('RecommendationComposeError has name', () => { const e = new RecommendationComposeError('m'); expect(e.name).toBe('RecommendationComposeError'); });
test('RecommendationComposeError is instanceof Error', () => { expect(new RecommendationComposeError('m')).toBeInstanceOf(Error); });
test('RecommendationComposeError is instanceof PackError', () => { expect(new RecommendationComposeError('m')).toBeInstanceOf(PackError); });
test('RecommendationComposeError has stack trace', () => { const e = new RecommendationComposeError('m'); expect(e.stack).toBeDefined(); });
test('RecommendationComposeError can be thrown and caught', () => { expect(() => { throw new RecommendationComposeError('test'); }).toThrow(RecommendationComposeError); });
test('RecommendationComposeError message matches', () => { expect(new RecommendationComposeError('hello').message).toBe('hello'); });
test('RecommendationChainError has code RECOMMENDATION_CHAIN_ERROR', () => { const e = new RecommendationChainError('m'); expect(e.code).toBe('RECOMMENDATION_CHAIN_ERROR'); });
test('RecommendationChainError default details is empty', () => { const e = new RecommendationChainError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('RecommendationChainError has stage field', () => { const e = new RecommendationChainError('Value','missing'); expect(e.stage).toBe('Value'); });
test('RecommendationChainError is instanceof Error', () => { expect(new RecommendationChainError('m')).toBeInstanceOf(Error); });
test('RecommendationChainError is instanceof PackError', () => { expect(new RecommendationChainError('m')).toBeInstanceOf(PackError); });
test('RecommendationChainError has stack trace', () => { const e = new RecommendationChainError('m'); expect(e.stack).toBeDefined(); });
test('RecommendationChainError can be thrown and caught', () => { expect(() => { throw new RecommendationChainError('test'); }).toThrow(RecommendationChainError); });
test('RecommendationChainError message contains stage', () => { const e = new RecommendationChainError('Constraint','reason'); expect(e.message).toContain('Constraint'); });
test('RecommendationChainError default reason', () => { const e = new RecommendationChainError('Value'); expect(e.message).toContain('unknown reason'); });
test('RecommendationNotFoundError has code RECOMMENDATION_NOT_FOUND', () => { const e = new RecommendationNotFoundError('m'); expect(e.code).toBe('RECOMMENDATION_NOT_FOUND'); });
test('RecommendationNotFoundError default details is empty', () => { const e = new RecommendationNotFoundError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('RecommendationNotFoundError has recommendationId', () => { const e = new RecommendationNotFoundError('r1'); expect(e.recommendationId).toBe('r1'); });
test('RecommendationNotFoundError is instanceof Error', () => { expect(new RecommendationNotFoundError('m')).toBeInstanceOf(Error); });
test('RecommendationNotFoundError is instanceof PackError', () => { expect(new RecommendationNotFoundError('m')).toBeInstanceOf(PackError); });
test('RecommendationNotFoundError has stack trace', () => { const e = new RecommendationNotFoundError('m'); expect(e.stack).toBeDefined(); });
test('RecommendationNotFoundError can be thrown and caught', () => { expect(() => { throw new RecommendationNotFoundError('test'); }).toThrow(RecommendationNotFoundError); });
test('RecommendationNotFoundError message contains id', () => { expect(new RecommendationNotFoundError('myr').message).toContain('myr'); });
test('KnowledgeNodeError has code KNOWLEDGE_NODE_ERROR', () => { const e = new KnowledgeNodeError('m'); expect(e.code).toBe('KNOWLEDGE_NODE_ERROR'); });
test('KnowledgeNodeError default details is empty', () => { const e = new KnowledgeNodeError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('KnowledgeNodeError has name', () => { const e = new KnowledgeNodeError('m'); expect(e.name).toBe('KnowledgeNodeError'); });
test('KnowledgeNodeError is instanceof Error', () => { expect(new KnowledgeNodeError('m')).toBeInstanceOf(Error); });
test('KnowledgeNodeError is instanceof PackError', () => { expect(new KnowledgeNodeError('m')).toBeInstanceOf(PackError); });
test('KnowledgeNodeError has stack trace', () => { const e = new KnowledgeNodeError('m'); expect(e.stack).toBeDefined(); });
test('KnowledgeNodeError can be thrown and caught', () => { expect(() => { throw new KnowledgeNodeError('test'); }).toThrow(KnowledgeNodeError); });
test('KnowledgeNodeError message matches', () => { expect(new KnowledgeNodeError('hello').message).toBe('hello'); });
test('KnowledgeNodeError default reason', () => { const e = new KnowledgeNodeError(); expect(e.message).toBe('Knowledge node operation failed'); });
test('KnowledgeEdgeError has code KNOWLEDGE_EDGE_ERROR', () => { const e = new KnowledgeEdgeError('m'); expect(e.code).toBe('KNOWLEDGE_EDGE_ERROR'); });
test('KnowledgeEdgeError default details is empty', () => { const e = new KnowledgeEdgeError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('KnowledgeEdgeError has name', () => { const e = new KnowledgeEdgeError('m'); expect(e.name).toBe('KnowledgeEdgeError'); });
test('KnowledgeEdgeError is instanceof Error', () => { expect(new KnowledgeEdgeError('m')).toBeInstanceOf(Error); });
test('KnowledgeEdgeError is instanceof PackError', () => { expect(new KnowledgeEdgeError('m')).toBeInstanceOf(PackError); });
test('KnowledgeEdgeError has stack trace', () => { const e = new KnowledgeEdgeError('m'); expect(e.stack).toBeDefined(); });
test('KnowledgeEdgeError can be thrown and caught', () => { expect(() => { throw new KnowledgeEdgeError('test'); }).toThrow(KnowledgeEdgeError); });
test('KnowledgeEdgeError message matches', () => { expect(new KnowledgeEdgeError('hello').message).toBe('hello'); });
test('KnowledgeEdgeError default reason', () => { const e = new KnowledgeEdgeError(); expect(e.message).toBe('Knowledge edge operation failed'); });
test('ConversationInterpretError has code CONVERSATION_INTERPRET_ERROR', () => { const e = new ConversationInterpretError('m'); expect(e.code).toBe('CONVERSATION_INTERPRET_ERROR'); });
test('ConversationInterpretError default details is empty', () => { const e = new ConversationInterpretError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('ConversationInterpretError has name', () => { const e = new ConversationInterpretError('m'); expect(e.name).toBe('ConversationInterpretError'); });
test('ConversationInterpretError is instanceof Error', () => { expect(new ConversationInterpretError('m')).toBeInstanceOf(Error); });
test('ConversationInterpretError is instanceof PackError', () => { expect(new ConversationInterpretError('m')).toBeInstanceOf(PackError); });
test('ConversationInterpretError has stack trace', () => { const e = new ConversationInterpretError('m'); expect(e.stack).toBeDefined(); });
test('ConversationInterpretError can be thrown and caught', () => { expect(() => { throw new ConversationInterpretError('test'); }).toThrow(ConversationInterpretError); });
test('ConversationInterpretError message matches', () => { expect(new ConversationInterpretError('hello').message).toBe('hello'); });
test('ConversationInterpretError default reason', () => { const e = new ConversationInterpretError(); expect(e.message).toBe('Conversation interpretation failed'); });
test('HabitInsightError has code HABIT_INSIGHT_ERROR', () => { const e = new HabitInsightError('m'); expect(e.code).toBe('HABIT_INSIGHT_ERROR'); });
test('HabitInsightError default details is empty', () => { const e = new HabitInsightError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('HabitInsightError has name', () => { const e = new HabitInsightError('m'); expect(e.name).toBe('HabitInsightError'); });
test('HabitInsightError is instanceof Error', () => { expect(new HabitInsightError('m')).toBeInstanceOf(Error); });
test('HabitInsightError is instanceof PackError', () => { expect(new HabitInsightError('m')).toBeInstanceOf(PackError); });
test('HabitInsightError has stack trace', () => { const e = new HabitInsightError('m'); expect(e.stack).toBeDefined(); });
test('HabitInsightError can be thrown and caught', () => { expect(() => { throw new HabitInsightError('test'); }).toThrow(HabitInsightError); });
test('HabitInsightError message matches', () => { expect(new HabitInsightError('hello').message).toBe('hello'); });
test('HabitInsightError default reason', () => { const e = new HabitInsightError(); expect(e.message).toBe('Habit insight operation failed'); });
test('PriorityCalculationError has code PRIORITY_CALCULATION_ERROR', () => { const e = new PriorityCalculationError('m'); expect(e.code).toBe('PRIORITY_CALCULATION_ERROR'); });
test('PriorityCalculationError default details is empty', () => { const e = new PriorityCalculationError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('PriorityCalculationError has goalId', () => { const e = new PriorityCalculationError('g1'); expect(e.goalId).toBe('g1'); });
test('PriorityCalculationError is instanceof Error', () => { expect(new PriorityCalculationError('m')).toBeInstanceOf(Error); });
test('PriorityCalculationError is instanceof PackError', () => { expect(new PriorityCalculationError('m')).toBeInstanceOf(PackError); });
test('PriorityCalculationError has stack trace', () => { const e = new PriorityCalculationError('m'); expect(e.stack).toBeDefined(); });
test('PriorityCalculationError can be thrown and caught', () => { expect(() => { throw new PriorityCalculationError('test'); }).toThrow(PriorityCalculationError); });
test('PriorityCalculationError message contains goalId', () => { expect(new PriorityCalculationError('mygoal').message).toContain('mygoal'); });
test('PriorityCalculationError with reason', () => { const e = new PriorityCalculationError('g1','missing factors'); expect(e.message).toContain('missing factors'); });
test('DashboardGenerationError has code DASHBOARD_GENERATION_ERROR', () => { const e = new DashboardGenerationError('m'); expect(e.code).toBe('DASHBOARD_GENERATION_ERROR'); });
test('DashboardGenerationError default details is empty', () => { const e = new DashboardGenerationError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('DashboardGenerationError has name', () => { const e = new DashboardGenerationError('m'); expect(e.name).toBe('DashboardGenerationError'); });
test('DashboardGenerationError is instanceof Error', () => { expect(new DashboardGenerationError('m')).toBeInstanceOf(Error); });
test('DashboardGenerationError is instanceof PackError', () => { expect(new DashboardGenerationError('m')).toBeInstanceOf(PackError); });
test('DashboardGenerationError has stack trace', () => { const e = new DashboardGenerationError('m'); expect(e.stack).toBeDefined(); });
test('DashboardGenerationError can be thrown and caught', () => { expect(() => { throw new DashboardGenerationError('test'); }).toThrow(DashboardGenerationError); });
test('DashboardGenerationError message matches', () => { expect(new DashboardGenerationError('hello').message).toBe('hello'); });
test('DashboardGenerationError default reason', () => { const e = new DashboardGenerationError(); expect(e.message).toBe('Dashboard generation failed'); });
test('FirstIntelligenceError has code FIRST_INTELLIGENCE_ERROR', () => { const e = new FirstIntelligenceError('m'); expect(e.code).toBe('FIRST_INTELLIGENCE_ERROR'); });
test('FirstIntelligenceError default details is empty', () => { const e = new FirstIntelligenceError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('FirstIntelligenceError has name', () => { const e = new FirstIntelligenceError('m'); expect(e.name).toBe('FirstIntelligenceError'); });
test('FirstIntelligenceError is instanceof Error', () => { expect(new FirstIntelligenceError('m')).toBeInstanceOf(Error); });
test('FirstIntelligenceError is instanceof PackError', () => { expect(new FirstIntelligenceError('m')).toBeInstanceOf(PackError); });
test('FirstIntelligenceError has stack trace', () => { const e = new FirstIntelligenceError('m'); expect(e.stack).toBeDefined(); });
test('FirstIntelligenceError can be thrown and caught', () => { expect(() => { throw new FirstIntelligenceError('test'); }).toThrow(FirstIntelligenceError); });
test('FirstIntelligenceError message matches', () => { expect(new FirstIntelligenceError('hello').message).toBe('hello'); });
test('FirstIntelligenceError default reason', () => { const e = new FirstIntelligenceError(); expect(e.message).toBe('First Intelligence experience failed'); });
test('PackDisposedError has code PACK_DISPOSED', () => { const e = new PackDisposedError(); expect(e.code).toBe('PACK_DISPOSED'); });
test('PackDisposedError default details is empty', () => { const e = new PackDisposedError(); expect(Object.keys(e.details).length).toBe(0); });
test('PackDisposedError has name', () => { const e = new PackDisposedError(); expect(e.name).toBe('PackDisposedError'); });
test('PackDisposedError is instanceof Error', () => { expect(new PackDisposedError()).toBeInstanceOf(Error); });
test('PackDisposedError is instanceof PackError', () => { expect(new PackDisposedError()).toBeInstanceOf(PackError); });
test('PackDisposedError has stack trace', () => { const e = new PackDisposedError(); expect(e.stack).toBeDefined(); });
test('PackDisposedError can be thrown and caught', () => { expect(() => { throw new PackDisposedError(); }).toThrow(PackDisposedError); });
test('PackDisposedError message', () => { expect(new PackDisposedError().message).toBe('Pack has been disposed'); });
test('PackStateError has code PACK_STATE_ERROR', () => { const e = new PackStateError('a','b'); expect(e.code).toBe('PACK_STATE_ERROR'); });
test('PackStateError default details is empty', () => { const e = new PackStateError('a','b'); expect(Object.keys(e.details).length).toBe(0); });
test('PackStateError has states', () => { const e = new PackStateError('Created','Active'); expect(e.currentState).toBe('Created'); expect(e.targetState).toBe('Active'); });
test('PackStateError is instanceof Error', () => { expect(new PackStateError('a','b')).toBeInstanceOf(Error); });
test('PackStateError is instanceof PackError', () => { expect(new PackStateError('a','b')).toBeInstanceOf(PackError); });
test('PackStateError has stack trace', () => { const e = new PackStateError('a','b'); expect(e.stack).toBeDefined(); });
test('PackStateError can be thrown and caught', () => { expect(() => { throw new PackStateError('a','b'); }).toThrow(PackStateError); });
test('PackStateError message contains states', () => { const e = new PackStateError('Old','New'); expect(e.message).toContain('Old'); expect(e.message).toContain('New'); });
test('ContractNotAvailableError has code CONTRACT_NOT_AVAILABLE', () => { const e = new ContractNotAvailableError('m'); expect(e.code).toBe('CONTRACT_NOT_AVAILABLE'); });
test('ContractNotAvailableError default details is empty', () => { const e = new ContractNotAvailableError('m'); expect(Object.keys(e.details).length).toBe(0); });
test('ContractNotAvailableError has contractName', () => { const e = new ContractNotAvailableError('memory'); expect(e.contractName).toBe('memory'); });
test('ContractNotAvailableError is instanceof Error', () => { expect(new ContractNotAvailableError('m')).toBeInstanceOf(Error); });
test('ContractNotAvailableError is instanceof PackError', () => { expect(new ContractNotAvailableError('m')).toBeInstanceOf(PackError); });
test('ContractNotAvailableError has stack trace', () => { const e = new ContractNotAvailableError('m'); expect(e.stack).toBeDefined(); });
test('ContractNotAvailableError can be thrown and caught', () => { expect(() => { throw new ContractNotAvailableError('test'); }).toThrow(ContractNotAvailableError); });
test('ContractNotAvailableError message contains name', () => { expect(new ContractNotAvailableError('mycontract').message).toContain('mycontract'); });
});
