import { describe, test, expect } from 'vitest';
import { PackMetricsRuntime } from '../../core/personal-intelligence/pack-metrics-runtime.js';
import { PackTraceRuntime } from '../../core/personal-intelligence/pack-trace-runtime.js';
import { PackMetricKey, TraceStatus } from '../../core/personal-intelligence/types.js';

const mp = { publishEvent: async () => {}, getConfiguration: () => null, getHealth: async () => null };
const mi = { getCurrentUserId: () => 'u1', getUserRoles: () => ['a'], getUserPreferences: () => ({}), resolvePreference: () => null };
const mm = { retrieve: async () => null, store: async () => {}, query: () => [], getSessionEntries: () => [], getWorkingEntries: () => [] };
const mk = { search: async () => [], getNamespaces: async () => [], getItemCount: async () => 0, getRecentItems: async () => [], getByTags: async () => [] };
const mw = { getActiveWorkflows: () => [], getRunningInstances: () => [], getRecentCompletions: () => [], getAvailableWorkflows: () => [] };
const mcg = { getCurrentIntent: () => null, getConversationTurnCount: () => 0, getCurrentSessionId: () => null, getConversationSummary: async () => null };
const mpe = { getGoals: () => [], getActiveGoals: () => [], getRecommendations: () => [], getHabits: () => [], getReflections: () => [], getDecisions: () => [], getAttentionState: () => 'Focused' };
const mai = { complete: async () => 'r', embed: async () => [0.1], isAvailable: () => true };
const mex = { getActiveAdaptations: () => [], getRecommendations: () => [], getCurrentPhase: () => 'O', getBehaviorPatterns: () => [] };
const C = { identity: mi, memory: mm, knowledge: mk, workflow: mw, cognitive: mcg, personal: mpe, aiProvider: mai, experience: mex, platform: mp };

describe('MetricsRuntime Deep', () => {
test('metrics: decrement works', () => { const m = new PackMetricsRuntime(); m.increment('a'); m.increment('a'); m.decrement('a'); expect(m.getCounter('a')).toBe(1); });
test('metrics: decrement below zero', () => { const m = new PackMetricsRuntime(); m.decrement('a'); expect(m.getCounter('a')).toBe(-1); });
test('metrics: missing counter returns 0', () => { const m = new PackMetricsRuntime(); expect(m.getCounter('missing')).toBe(0); });
test('metrics: missing gauge returns 0', () => { const m = new PackMetricsRuntime(); expect(m.getGauge('missing')).toBe(0); });
test('metrics: setGauge overwrites', () => { const m = new PackMetricsRuntime(); m.setGauge('g', 10); m.setGauge('g', 20); expect(m.getGauge('g')).toBe(20); });
test('metrics: series is ordered by time', () => { const m = new PackMetricsRuntime(); m.recordSeries('s', 1); m.recordSeries('s', 2); m.recordSeries('s', 3); const s = m.getSeries('s'); expect(s[0].value).toBe(1); expect(s[1].value).toBe(2); expect(s[2].value).toBe(3); });
test('metrics: missing series returns empty', () => { const m = new PackMetricsRuntime(); expect(m.getSeries('missing').length).toBe(0); });
test('metrics: snapshot is frozen', () => { const m = new PackMetricsRuntime(); m.increment('c'); const s = m.getSnapshot(); expect(Object.isFrozen(s)).toBe(true); });
test('metrics: snapshot has exportedAt', () => { const m = new PackMetricsRuntime(); const s = m.getSnapshot(); expect(s.exportedAt).toBeTruthy(); });
test('metrics: export is valid JSON', () => { const m = new PackMetricsRuntime(); m.increment('x'); m.setGauge('y', 5); const j = JSON.parse(m.export()); expect(j.counters.x).toBe(1); expect(j.gauges.y).toBe(5); });
test('metrics: convenience getters work', () => { const m = new PackMetricsRuntime(); m.setGauge('productivity_index', 72); m.setGauge('development_index', 65); expect(m.getProductivityIndex()).toBe(72); expect(m.getDevelopmentIndex()).toBe(65); });
test('metrics: increment briefs_generated', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.briefs_generated); expect(m.getCounter(PackMetricKey.briefs_generated)).toBe(1); });
test('metrics: getCounter for briefs_generated before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.briefs_generated)).toBe(0); });
test('metrics: increment reflections_generated', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.reflections_generated); expect(m.getCounter(PackMetricKey.reflections_generated)).toBe(1); });
test('metrics: getCounter for reflections_generated before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.reflections_generated)).toBe(0); });
test('metrics: increment goals_created', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.goals_created); expect(m.getCounter(PackMetricKey.goals_created)).toBe(1); });
test('metrics: getCounter for goals_created before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.goals_created)).toBe(0); });
test('metrics: increment goals_completed', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.goals_completed); expect(m.getCounter(PackMetricKey.goals_completed)).toBe(1); });
test('metrics: getCounter for goals_completed before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.goals_completed)).toBe(0); });
test('metrics: increment decisions_created', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.decisions_created); expect(m.getCounter(PackMetricKey.decisions_created)).toBe(1); });
});

describe('TraceRuntime Deep', () => {
test('metrics: getCounter for decisions_created before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.decisions_created)).toBe(0); });
test('metrics: increment decisions_resolved', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.decisions_resolved); expect(m.getCounter(PackMetricKey.decisions_resolved)).toBe(1); });
test('metrics: getCounter for decisions_resolved before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.decisions_resolved)).toBe(0); });
test('metrics: increment constraints_detected', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.constraints_detected); expect(m.getCounter(PackMetricKey.constraints_detected)).toBe(1); });
test('metrics: getCounter for constraints_detected before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.constraints_detected)).toBe(0); });
test('metrics: increment constraints_resolved', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.constraints_resolved); expect(m.getCounter(PackMetricKey.constraints_resolved)).toBe(1); });
test('metrics: getCounter for constraints_resolved before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.constraints_resolved)).toBe(0); });
test('metrics: increment value_assessments', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.value_assessments); expect(m.getCounter(PackMetricKey.value_assessments)).toBe(1); });
test('metrics: getCounter for value_assessments before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.value_assessments)).toBe(0); });
test('metrics: increment recommendations_composed', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.recommendations_composed); expect(m.getCounter(PackMetricKey.recommendations_composed)).toBe(1); });
test('metrics: getCounter for recommendations_composed before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.recommendations_composed)).toBe(0); });
test('metrics: increment recommendations_accepted', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.recommendations_accepted); expect(m.getCounter(PackMetricKey.recommendations_accepted)).toBe(1); });
test('metrics: getCounter for recommendations_accepted before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.recommendations_accepted)).toBe(0); });
test('metrics: increment recommendations_rejected', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.recommendations_rejected); expect(m.getCounter(PackMetricKey.recommendations_rejected)).toBe(1); });
test('metrics: getCounter for recommendations_rejected before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.recommendations_rejected)).toBe(0); });
test('metrics: increment knowledge_nodes_created', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.knowledge_nodes_created); expect(m.getCounter(PackMetricKey.knowledge_nodes_created)).toBe(1); });
test('metrics: getCounter for knowledge_nodes_created before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.knowledge_nodes_created)).toBe(0); });
test('metrics: increment knowledge_edges_created', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.knowledge_edges_created); expect(m.getCounter(PackMetricKey.knowledge_edges_created)).toBe(1); });
test('metrics: getCounter for knowledge_edges_created before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.knowledge_edges_created)).toBe(0); });
test('metrics: increment conversations_interpreted', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.conversations_interpreted); expect(m.getCounter(PackMetricKey.conversations_interpreted)).toBe(1); });
test('metrics: getCounter for conversations_interpreted before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.conversations_interpreted)).toBe(0); });
test('metrics: increment habits_detected', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.habits_detected); expect(m.getCounter(PackMetricKey.habits_detected)).toBe(1); });
test('metrics: getCounter for habits_detected before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.habits_detected)).toBe(0); });
test('metrics: increment priorities_calculated', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.priorities_calculated); expect(m.getCounter(PackMetricKey.priorities_calculated)).toBe(1); });
test('metrics: getCounter for priorities_calculated before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.priorities_calculated)).toBe(0); });
test('metrics: increment dashboards_generated', () => { const m = new PackMetricsRuntime(); m.increment(PackMetricKey.dashboards_generated); expect(m.getCounter(PackMetricKey.dashboards_generated)).toBe(1); });
test('metrics: getCounter for dashboards_generated before increment', () => { const m = new PackMetricsRuntime(); expect(m.getCounter(PackMetricKey.dashboards_generated)).toBe(0); });
test('trace: startSpan with attributes', () => { const t = new PackTraceRuntime(); const s = t.startSpan('op', 'sub', undefined, {key:'val',num:42}); expect(s.attributes).toEqual({key:'val',num:42}); });
test('trace: startSpan with parentId', () => { const t = new PackTraceRuntime(); const p = t.startSpan('parent', 'sub'); const c = t.startSpan('child', 'sub', p.id as unknown as string); expect(c.parentId).toBe(p.id); });
test('trace: activateSpan is idempotent', () => { const t = new PackTraceRuntime(); const s = t.startSpan('op', 'sub'); t.activateSpan(s.id as unknown as string); t.activateSpan(s.id as unknown as string); expect(t.getActiveSpans().length).toBe(1); });
test('trace: completeSpan calculates duration', () => { const t = new PackTraceRuntime(); const s = t.startSpan('op', 'sub'); t.completeSpan(s.id as unknown as string); const c = t.getSpan(s.id as unknown as string); expect(c.durationMs).toBeGreaterThanOrEqual(0); });
test('trace: failSpan calculates duration', () => { const t = new PackTraceRuntime(); const s = t.startSpan('op', 'sub'); t.failSpan(s.id as unknown as string); const f = t.getSpan(s.id as unknown as string); expect(f.durationMs).toBeGreaterThanOrEqual(0); });
test('trace: getSpansByOperation', () => { const t = new PackTraceRuntime(); t.startSpan('genBrief', 'DailyBrief'); t.startSpan('genBrief', 'DailyBrief'); t.startSpan('other', 'Goal'); expect(t.getSpansByOperation('genBrief').length).toBe(2); });
test('trace: getAverageDurationMs for subsystem', () => { const t = new PackTraceRuntime(); const s = t.startSpan('op', 'MySub'); t.completeSpan(s.id as unknown as string); expect(t.getAverageDurationMs('MySub')).toBeGreaterThanOrEqual(0); });
test('trace: getSpan throws for invalid id', () => { const t = new PackTraceRuntime(); expect(() => t.getSpan('invalid')).toThrow(); });
test('trace: addSpanEvent to completed span', () => { const t = new PackTraceRuntime(); const s = t.startSpan('op', 'sub'); t.completeSpan(s.id as unknown as string); const u = t.addSpanEvent(s.id as unknown as string, 'post-complete', {}); expect(u.events.length).toBe(1); });
test('trace: multiple events on span', () => { const t = new PackTraceRuntime(); const s = t.startSpan('op', 'sub'); t.addSpanEvent(s.id as unknown as string, 'e1'); t.addSpanEvent(s.id as unknown as string, 'e2'); expect(t.getSpan(s.id as unknown as string).events.length).toBe(2); });
test('trace: getAverageDurationMs returns 0 for no completed', () => { const t = new PackTraceRuntime(); expect(t.getAverageDurationMs()).toBe(0); });
test('trace: getAverageDurationMs for subsystem returns 0 when none', () => { const t = new PackTraceRuntime(); expect(t.getAverageDurationMs('NoSub')).toBe(0); });
});
