export function assert(condition: boolean, message: string): void { if (!condition) throw new Error(`Assertion failed: ${message}`); }
export function assertEqual<T>(actual: T, expected: T, message?: string): void { if (actual !== expected) throw new Error(`${message ?? ''} Expected ${JSON.stringify(expected)} but got ${JSON.stringify(actual)}`); }
export function assertNull(actual: unknown, message?: string): void { if (actual !== null && actual !== undefined) throw new Error(`${message ?? ''} Expected null/undefined`); }
export function assertNotNull<T>(actual: T | null | undefined, message?: string): void { if (actual === null || actual === undefined) throw new Error(`${message ?? ''} Expected non-null value`); }
export function assertThrows(fn: () => void, code?: string): void { try { fn(); throw new Error('Expected function to throw but it did not'); } catch (err) { if (err instanceof Error && err.message === 'Expected function to throw but it did not') throw err; if (code && err instanceof Error && 'code' in err && (err as Error & { code: string }).code !== code) throw new Error(`Expected error code '${code}' but got '${(err as Error & { code: string }).code}'`); } }
export async function assertThrowsAsync(fn: () => Promise<void>, code?: string): Promise<void> { try { await fn(); throw new Error('Expected function to throw but it did not'); } catch (err) { if (err instanceof Error && err.message === 'Expected function to throw but it did not') throw err; if (code && err instanceof Error && 'code' in err && (err as Error & { code: string }).code !== code) throw new Error(`Expected error code '${code}' but got '${(err as Error & { code: string }).code}'`); } }
export interface TestResult { name: string; passed: boolean; error?: string; }
export async function runTests(tests: Array<{ name: string; fn: () => void | Promise<void> }>): Promise<TestResult[]> { const results: TestResult[] = []; for (const test of tests) { try { await test.fn(); results.push({ name: test.name, passed: true }); } catch (err) { results.push({ name: test.name, passed: false, error: err instanceof Error ? err.message : String(err) }); } } return results; }
export function printResults(results: TestResult[]): void { const passed = results.filter(r => r.passed).length; const failed = results.filter(r => !r.passed).length; console.log(`\n  Tests: ${passed} passed, ${failed} failed, ${results.length} total`); for (const r of results) { console.log(`  ${r.passed ? '✓' : '✗'} ${r.name}${r.error ? ` — ${r.error}` : ''}`); } }
