/**
 * SIP Server — Report Generator
 * Reports built exclusively from Findings. No demo data.
 * Export: JSON, SARIF, Markdown, CSV, HTML.
 */

import type { Finding, AIRecommendation, ReportType } from "../types";
import { generateRecommendations } from "./recommendations";

export interface ReportContent {
  executiveSummary?: string;
  technicalDetails?: string;
  complianceStatus?: Record<string, number>;
  findings: Finding[];
  riskScore: number;
  recommendations: AIRecommendation[];
}

export function generateReport(
  type: ReportType,
  findings: Finding[],
  riskScore: number,
  projectName: string,
): ReportContent {
  const recommendations = generateRecommendations(findings);

  const content: ReportContent = {
    findings,
    riskScore,
    recommendations,
  };

  if (type === "executive") {
    content.executiveSummary = buildExecutiveSummary(findings, riskScore, projectName);
  } else if (type === "technical") {
    content.technicalDetails = buildTechnicalDetails(findings);
  } else if (type === "compliance") {
    content.complianceStatus = buildComplianceStatus(findings);
  }

  return content;
}

function buildExecutiveSummary(findings: Finding[], riskScore: number, projectName: string): string {
  const critical = findings.filter((f) => f.severity === "critical").length;
  const high = findings.filter((f) => f.severity === "high").length;
  const medium = findings.filter((f) => f.severity === "medium").length;
  const low = findings.filter((f) => f.severity === "low").length;
  const total = findings.length;
  const riskLevel = riskScore >= 80 ? "CRITICAL" : riskScore >= 60 ? "HIGH" : riskScore >= 30 ? "MEDIUM" : "LOW";

  return `Security Assessment — ${projectName}

Overall Risk Score: ${riskScore}/100 (${riskLevel})

Summary of Findings:
- Critical: ${critical}
- High: ${high}
- Medium: ${medium}
- Low: ${low}
- Total: ${total}

${critical > 0 ? `URGENT: ${critical} critical vulnerabilities require immediate attention.` : "No critical vulnerabilities were identified."}

Key Recommendations:
1. ${critical > 0 ? "Address all critical findings immediately" : "Continue monitoring for new vulnerabilities"}
2. ${high > 0 ? "Remediate high-severity findings within 7 days" : "Review medium-severity findings"}
3. Implement a regular scanning schedule
4. Ensure all dependencies are kept up to date

Generated by SIP — Security Intelligence Platform.`;
}

function buildTechnicalDetails(findings: Finding[]): string {
  const sections = findings.map((f) => {
    const lines: string[] = [];
    lines.push(`### ${f.id}: ${f.title}`);
    lines.push(`- Severity: ${f.severity.toUpperCase()} (CVSS: ${f.cvss})`);
    lines.push(`- Asset: ${f.asset}`);
    lines.push(`- Tool: ${f.tool}`);
    if (f.cve) lines.push(`- CVE: ${f.cve}`);
    if (f.cwe) lines.push(`- CWE: ${f.cwe}`);
    lines.push("");
    lines.push(`**Description:** ${f.description}`);
    lines.push(`**Evidence:** ${f.evidence}`);
    lines.push(`**Recommendation:** ${f.recommendation}`);
    return lines.join("\n");
  });
  return sections.join("\n\n---\n\n");
}

function buildComplianceStatus(findings: Finding[]): Record<string, number> {
  const owaspFailures = new Set<string>();
  for (const f of findings) {
    if (f.cwe === "89") owaspFailures.add("A1");
    if (f.cwe === "798") owaspFailures.add("A2");
    if (f.cwe === "79") owaspFailures.add("A3");
    if (f.severity === "critical" || f.severity === "high") owaspFailures.add("A5");
    if (f.tool === "nmap") owaspFailures.add("A6");
    if (f.cwe === "1004") owaspFailures.add("A7");
  }

  return {
    "OWASP Top 10": Math.max(0, 100 - owaspFailures.size * 12),
    "PCI-DSS": Math.max(0, 100 - findings.filter((f) => f.severity === "critical").length * 25),
    "SOC 2": Math.max(0, 100 - findings.filter((f) => f.severity === "critical" || f.severity === "high").length * 10),
    "ISO 27001": Math.max(0, 100 - findings.length * 5),
    "NIST CSF": Math.max(0, 100 - findings.filter((f) => f.severity !== "info" && f.severity !== "low").length * 8),
  };
}

// ─── Export Formats ───────────────────────────────────────────────────────

export function exportAsJSON(content: ReportContent): string {
  return JSON.stringify(content, null, 2);
}

export function exportAsSARIF(findings: Finding[]): string {
  const sarif = {
    $schema: "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
    version: "2.1.0",
    runs: [{
      tool: {
        driver: {
          name: "SIP — Security Intelligence Platform",
          version: "1.0.0",
          informationUri: "https://sec-scanner.pro",
        },
      },
      results: findings.map((f) => ({
        ruleId: f.cwe ? `CWE-${f.cwe}` : f.tool,
        level: f.severity === "critical" ? "error" : f.severity === "high" ? "error" : f.severity === "medium" ? "warning" : "note",
        message: { text: f.description },
        locations: [{ physicalLocation: { artifactLocation: { uri: f.asset } } }],
        fingerprints: { id: f.id },
        properties: { cvss: f.cvss, cve: f.cve, tool: f.tool, recommendation: f.recommendation },
      })),
    }],
  };
  return JSON.stringify(sarif, null, 2);
}

export function exportAsMarkdown(content: ReportContent, type: ReportType, projectName: string): string {
  const lines: string[] = [];
  lines.push(`# ${type === "executive" ? "Executive" : type === "technical" ? "Technical" : "Compliance"} Report — ${projectName}`);
  lines.push("");
  lines.push(`**Risk Score:** ${content.riskScore}/100`);
  lines.push(`**Findings:** ${content.findings.length}`);
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push("");

  if (content.executiveSummary) {
    lines.push(content.executiveSummary);
    lines.push("");
  }

  if (content.technicalDetails) {
    lines.push(content.technicalDetails);
    lines.push("");
  }

  if (content.complianceStatus) {
    lines.push("## Compliance Status");
    lines.push("");
    for (const [framework, score] of Object.entries(content.complianceStatus)) {
      lines.push(`- **${framework}:** ${score}%`);
    }
    lines.push("");
  }

  lines.push("## Recommendations");
  lines.push("");
  for (const rec of content.recommendations) {
    const finding = content.findings.find((f) => f.id === rec.findingId);
    lines.push(`### ${finding?.title || rec.findingId} [${rec.priority.toUpperCase()}]`);
    lines.push(`- **Risk:** ${rec.riskExplanation}`);
    lines.push(`- **Recommendation:** ${rec.recommendation}`);
    lines.push(`- **Plan:** ${rec.remediationPlan}`);
    lines.push(`- **Business Impact:** ${rec.businessImpact}`);
    lines.push(`- **Estimated Effort:** ${rec.estimatedEffort}`);
    lines.push("");
  }

  return lines.join("\n");
}

export function exportAsCSV(findings: Finding[]): string {
  const headers = ["ID", "Tool", "Asset", "Severity", "Title", "CVSS", "CWE", "CVE", "Description", "Recommendation", "Status"];
  const rows = findings.map((f) => [
    f.id, f.tool, f.asset, f.severity, `"${f.title.replace(/"/g, '""')}"`,
    String(f.cvss), f.cwe || "", f.cve || "",
    `"${f.description.replace(/"/g, '""')}"`,
    `"${f.recommendation.replace(/"/g, '""')}"`,
    f.status,
  ].join(","));
  return [headers.join(","), ...rows].join("\n");
}

export function exportAsHTML(content: ReportContent, type: ReportType, projectName: string): string {
  const severityColors: Record<string, string> = {
    critical: "#dc2626", high: "#d97706", medium: "#f59e0b", low: "#22c55e", info: "#06b6d4",
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>SIP Report — ${projectName}</title>
  <style>
    body { font-family: -apple-system, system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }
    h1 { border-bottom: 2px solid #00d4ff; padding-bottom: 0.5rem; }
    .risk-score { font-size: 2rem; font-weight: bold; color: ${content.riskScore >= 80 ? "#dc2626" : content.riskScore >= 60 ? "#d97706" : "#22c55e"}; }
    .finding { border: 1px solid #e5e7eb; border-radius: 8px; padding: 1rem; margin: 1rem 0; }
    .severity { display: inline-block; padding: 2px 8px; border-radius: 4px; color: white; font-size: 0.75rem; font-weight: bold; }
    table { width: 100%; border-collapse: collapse; }
    th, td { text-align: left; padding: 8px; border-bottom: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <h1>${type === "executive" ? "Executive" : type === "technical" ? "Technical" : "Compliance"} Report</h1>
  <p><strong>Project:</strong> ${projectName}</p>
  <p><strong>Risk Score:</strong> <span class="risk-score">${content.riskScore}/100</span></p>
  <p><strong>Findings:</strong> ${content.findings.length}</p>
  <p><strong>Generated:</strong> ${new Date().toISOString()}</p>

  ${content.executiveSummary ? `<h2>Executive Summary</h2><pre style="white-space: pre-wrap;">${content.executiveSummary}</pre>` : ""}

  <h2>Findings</h2>
  ${content.findings.map((f) => `
    <div class="finding">
      <h3>${f.id}: ${f.title} <span class="severity" style="background:${severityColors[f.severity]}">${f.severity.toUpperCase()}</span></h3>
      <p><strong>Asset:</strong> ${f.asset} | <strong>CVSS:</strong> ${f.cvss} | <strong>Tool:</strong> ${f.tool}</p>
      <p>${f.description}</p>
      <p><strong>Recommendation:</strong> ${f.recommendation}</p>
      ${f.evidence ? `<p><strong>Evidence:</strong> <code>${f.evidence}</code></p>` : ""}
    </div>
  `).join("")}

  <footer style="margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 0.875rem;">
    Generated by SIP — Security Intelligence Platform
  </footer>
</body>
</html>`;
}
