import type { PlatformConfiguration } from './types.js';

export const DEFAULT_CONFIGURATION: PlatformConfiguration = {
  server: {
    host: '0.0.0.0',
    port: 8080,
    cors: true,
    corsOrigins: ['*'],
    compression: true,
    requestBodyLimit: '10mb',
    requestTimeout: 30000,
    gracefulShutdownTimeout: 10000,
  },
  auth: {
    enabled: false,
    provider: 'none',
    jwt: {
      secret: '',
      algorithm: 'HS256',
      issuer: 'security-intelligence-platform',
      audience: 'si-platform',
      accessTokenTtl: '15m',
      refreshTokenTtl: '7d',
    },
    apiKey: {
      header: 'x-api-key',
      queryParam: 'api_key',
      keys: [],
    },
    oauth2: {
      issuerUrl: '',
      clientId: '',
      clientSecret: '',
      scopes: ['openid', 'profile'],
      redirectUri: 'http://localhost:8080/auth/callback',
    },
    session: {
      cookieName: 'si-session',
      cookieSecure: true,
      cookieHttpOnly: true,
      cookieSameSite: 'strict',
      ttl: '24h',
    },
  },
  persistence: {
    backend: 'json',
    dataDir: './data/si-platform',
    connection: {
      host: 'localhost',
      port: 5432,
      database: 'siplatform',
      username: '',
      password: '',
      ssl: false,
      sslCert: '',
    },
    pool: {
      min: 2,
      max: 10,
      idleTimeout: 30000,
    },
    snapshot: {
      enabled: true,
      directory: './data/snapshots',
      format: 'json',
      retention: 30,
    },
    migration: {
      autoRun: true,
      directory: './migrations',
    },
  },
  analysis: {
    defaultOptions: {
      explain: true,
      includeAttackPaths: true,
      includeImpact: true,
      persist: false,
    },
    pipeline: {
      maxConcurrent: 1,
      stageTimeout: 60000,
      retryAttempts: 2,
      retryDelay: 1000,
    },
    risk: {
      severityWeight: 0.35,
      confidenceWeight: 0.15,
      exposureWeight: 0.20,
      impactWeight: 0.15,
      exploitabilityWeight: 0.15,
      correlationMultiplier: 1.5,
    },
    attackPath: {
      maxDepth: 10,
      maxPaths: 50,
      minRiskScore: 20,
    },
  },
  observability: {
    enabled: true,
    tracing: {
      enabled: false,
      provider: 'none',
      endpoint: 'http://localhost:14268/api/traces',
      sampleRate: 0.1,
    },
    metrics: {
      enabled: true,
      provider: 'prometheus',
      path: '/metrics',
      defaultLabels: { app: 'si-platform' },
    },
    logging: {
      level: 'info',
      format: 'json',
      output: 'stdout',
      filePath: './logs/si-platform.log',
    },
  },
  security: {
    rateLimit: {
      enabled: true,
      maxRequests: 100,
      windowMs: 60000,
      skipSuccessfulRequests: false,
    },
    headers: {
      enabled: true,
      contentSecurityPolicy: "default-src 'self'",
      strictTransportSecurity: 'max-age=31536000; includeSubDomains',
      xFrameOptions: 'DENY',
      xContentTypeOptions: 'nosniff',
      referrerPolicy: 'strict-origin-when-cross-origin',
    },
    cors: {
      enabled: true,
      origins: ['*'],
      methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'],
      allowedHeaders: ['Content-Type', 'Authorization', 'X-Request-ID'],
      exposedHeaders: ['X-Request-ID', 'X-Response-Time'],
      credentials: false,
      maxAge: 86400,
    },
    payload: {
      maxJsonSize: '10mb',
      maxFindingsPerRequest: 10000,
      sanitizeHtml: true,
    },
  },
  plugins: {
    directory: './plugins',
    autoLoad: false,
    enabled: [],
    disabled: [],
  },
  audit: {
    enabled: true,
    backend: 'json',
    directory: './data/audit',
    retention: 90,
    logInternal: false,
  },
  jobs: {
    enabled: true,
    backend: 'memory',
    concurrency: 4,
    retryAttempts: 3,
    retryDelay: 5000,
    cleanupInterval: 60000,
  },
  $meta: {
    version: 2,
    source: {},
    loadedAt: new Date().toISOString(),
    filePath: '',
    checksum: '',
  },
};
