import type { ConfigSchema, ConfigPropertySchema } from './types.js';

export const PLATFORM_CONFIG_SCHEMA: ConfigSchema = {
  $id: 'si-platform-config',
  $version: 2,
  properties: {
    'server.host': { type: 'string', description: 'Server bind host', default: '0.0.0.0', env: 'SI_SERVER_HOST', cliFlag: '--host' },
    'server.port': { type: 'number', description: 'Server bind port', default: 8080, env: 'SI_SERVER_PORT', cliFlag: '--port', min: 1, max: 65535 },
    'server.cors': { type: 'boolean', description: 'Enable CORS', default: true, env: 'SI_CORS' },
    'server.compression': { type: 'boolean', description: 'Enable response compression', default: true },
    'server.requestBodyLimit': { type: 'string', description: 'Max request body size', default: '10mb', env: 'SI_REQUEST_BODY_LIMIT' },
    'server.requestTimeout': { type: 'number', description: 'Request timeout in ms', default: 30000, min: 1000, max: 300000 },
    'auth.enabled': { type: 'boolean', description: 'Enable authentication', default: false, env: 'SI_AUTH_ENABLED' },
    'auth.provider': { type: 'string', description: 'Auth provider', default: 'none', env: 'SI_AUTH_PROVIDER', enum: ['none', 'jwt', 'api-key', 'oauth2'] },
    'auth.jwt.secret': { type: 'string', description: 'JWT signing secret', default: '', env: 'SI_JWT_SECRET', secret: true },
    'auth.jwt.algorithm': { type: 'string', description: 'JWT algorithm', default: 'HS256', enum: ['HS256', 'HS384', 'HS512', 'RS256', 'RS384', 'RS512'] },
    'auth.jwt.issuer': { type: 'string', description: 'JWT issuer', default: 'security-intelligence-platform' },
    'auth.jwt.accessTokenTtl': { type: 'string', description: 'Access token TTL', default: '15m' },
    'persistence.backend': { type: 'string', description: 'Persistence backend', default: 'json', env: 'SI_PERSISTENCE_BACKEND', enum: ['json', 'sqlite', 'postgres', 'neo4j', 'redis'] },
    'persistence.dataDir': { type: 'string', description: 'Data directory', default: './data/si-platform', env: 'SI_DATA_DIR' },
    'persistence.connection.host': { type: 'string', description: 'DB host', default: 'localhost', env: 'SI_DB_HOST' },
    'persistence.connection.port': { type: 'number', description: 'DB port', default: 5432, env: 'SI_DB_PORT' },
    'persistence.connection.username': { type: 'string', description: 'DB username', default: '', env: 'SI_DB_USER' },
    'persistence.connection.password': { type: 'string', description: 'DB password', default: '', env: 'SI_DB_PASSWORD', secret: true },
    'analysis.risk.severityWeight': { type: 'number', description: 'Severity factor weight', default: 0.35, min: 0, max: 1 },
    'analysis.risk.confidenceWeight': { type: 'number', description: 'Confidence factor weight', default: 0.15, min: 0, max: 1 },
    'observability.enabled': { type: 'boolean', description: 'Enable observability', default: true, env: 'SI_OBSERVABILITY_ENABLED' },
    'observability.logging.level': { type: 'string', description: 'Log level', default: 'info', env: 'SI_LOG_LEVEL', enum: ['trace', 'debug', 'info', 'warn', 'error', 'fatal'] },
    'observability.tracing.enabled': { type: 'boolean', description: 'Enable distributed tracing', default: false, env: 'SI_TRACING_ENABLED' },
    'observability.tracing.provider': { type: 'string', description: 'Tracing provider', default: 'none', enum: ['none', 'jaeger', 'otlp'] },
    'security.rateLimit.enabled': { type: 'boolean', description: 'Enable rate limiting', default: true, env: 'SI_RATE_LIMIT_ENABLED' },
    'security.rateLimit.maxRequests': { type: 'number', description: 'Max requests per window', default: 100, min: 1, max: 100000 },
    'audit.enabled': { type: 'boolean', description: 'Enable audit logging', default: true, env: 'SI_AUDIT_ENABLED' },
    'jobs.enabled': { type: 'boolean', description: 'Enable background jobs', default: true, env: 'SI_JOBS_ENABLED' },
    'jobs.concurrency': { type: 'number', description: 'Max concurrent jobs', default: 4, min: 1, max: 32 },
    'plugins.autoLoad': { type: 'boolean', description: 'Auto-load plugins', default: false, env: 'SI_PLUGINS_AUTOLOAD' },
  },
};
