#!/usr/bin/env python3
"""Generate batch 5 to reach 1500+ for TASK-AIS-007A.000."""

import os

TEST_DIR = "/home/z/my-project/src/__tests__/personal-intelligence"

def w(name, content):
    path = os.path.join(TEST_DIR, name)
    with open(path, "w") as f:
        f.write(content)
    print(f"  Created {name} ({content.count('test(')} tests)")

def mc():
    return """const mp = { publishEvent: async () => {}, getConfiguration: () => null, getHealth: async () => null };
const mi = { getCurrentUserId: () => 'u1', getUserRoles: () => ['a'], getUserPreferences: () => ({}), resolvePreference: () => null };
const mm = { retrieve: async () => null, store: async () => {}, query: () => [], getSessionEntries: () => [], getWorkingEntries: () => [] };
const mk = { search: async () => [], getNamespaces: async () => [], getItemCount: async () => 0, getRecentItems: async () => [], getByTags: async () => [] };
const mw = { getActiveWorkflows: () => [], getRunningInstances: () => [], getRecentCompletions: () => [], getAvailableWorkflows: () => [] };
const mcg = { getCurrentIntent: () => null, getConversationTurnCount: () => 0, getCurrentSessionId: () => null, getConversationSummary: async () => null };
const mpe = { getGoals: () => [], getActiveGoals: () => [], getRecommendations: () => [], getHabits: () => [], getReflections: () => [], getDecisions: () => [], getAttentionState: () => 'Focused' };
const mai = { complete: async () => 'r', embed: async () => [0.1], isAvailable: () => true };
const mex = { getActiveAdaptations: () => [], getRecommendations: () => [], getCurrentPhase: () => 'O', getBehaviorPatterns: () => [] };
const C = { identity: mi, memory: mm, knowledge: mk, workflow: mw, cognitive: mcg, personal: mpe, aiProvider: mai, experience: mex, platform: mp };
"""

def gen_integration():
    tests = []
    # Full pack workflow tests
    tests.append("""test('integration: complete morning workflow', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); const brief = r.generateMorningBrief(); const goal = r.goalPlanner.createGoal({title:'Daily top priority',level:GoalLevel.Tasks}); const constraint = r.constraintAnalyzer.detectConstraint('Delivery bottleneck','Too many meetings',ConstraintSeverity.Major,'goal-1'); const value = r.valueAnalyzer.createAssessment(ValueDimension.UserValue,'Free up 2h focus time',['Reduce meetings'],'User',['Hours saved'],'Better deep work sessions',0.85); const rec = r.recommendationComposer.composeRecommendation('Reduce meeting time','Block 2h of focus time daily',{why:'Meetings are the main constraint on delivery',whyNow:'Sprint deadline is this week',whatValue:'UserValue - 2h of deep work daily',whyMainConstraint:'Too many meetings'},value.id as unknown as string,constraint.id as unknown as string,goal.id as unknown as string,0.9); r.recommendationComposer.present(rec.id as unknown as string); r.recommendationComposer.accept(rec.id as unknown as string); const knowledge = r.knowledgeSynthesizer.addNode(KnowledgeNodeType.Conclusion,'Meetings are the #1 bottleneck','Analysis shows 60% of time in meetings','decision-analysis'); expect(brief.items.length).toBeGreaterThan(0); expect(goal.id).toBeTruthy(); expect(constraint.id).toBeTruthy(); expect(value.id).toBeTruthy(); expect(rec.id).toBeTruthy(); expect(knowledge.id).toBeTruthy(); expect(r.metrics.getCounter('briefs_generated')).toBe(1); expect(r.metrics.getCounter('goals_created')).toBe(1); expect(r.metrics.getCounter('constraints_detected')).toBe(1); expect(r.metrics.getCounter('recommendations_composed')).toBe(1); expect(r.metrics.getCounter('recommendations_accepted')).toBe(1); expect(r.metrics.getCounter('knowledge_nodes_created')).toBe(1); r.dispose(); });""")
    tests.append("""test('integration: evening reflection with goal completion', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); const g = r.goalPlanner.createGoal({title:'Ship feature',level:GoalLevel.Tasks}); r.goalPlanner.setStatus(g.id as unknown as string, GoalStatus.Active); r.goalPlanner.setStatus(g.id as unknown as string, GoalStatus.InProgress); r.goalPlanner.setStatus(g.id as unknown as string, GoalStatus.Completed); const ref = r.generateEveningReflection(); expect(ref.accomplishments.length).toBeGreaterThan(0); expect(r.metrics.getCounter('goals_completed')).toBe(1); expect(r.metrics.getCounter('reflections_generated')).toBe(1); r.dispose(); });""")
    tests.append("""test('integration: decision with constraint', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); const d = r.decisionAdvisor.createDecision('Choose technology','Which framework to use',['React','Vue','Svelte']); r.decisionAdvisor.addAnalysis(d.id as unknown as string, 0, {pros:['Large ecosystem','Type safety'],cons:['Complexity'],risks:['Burnout'],alternatives:['Svelte'],consequences:['Longer build times']}); const constraint = r.constraintAnalyzer.detectConstraint('Skill gap','Team lacks React experience',ConstraintSeverity.Major); r.decisionAdvisor.resolve(d.id as unknown as string, 'React due to team skills and ecosystem'); expect(r.metrics.getCounter('decisions_created')).toBe(1); expect(r.metrics.getCounter('decisions_resolved')).toBe(1); expect(r.metrics.getCounter('constraints_detected')).toBe(1); r.dispose(); });""")
    tests.append("""test('integration: habit tracking with knowledge', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); const h = r.habitInsights.detectHabit('Context switching','Switches between tasks every 10 min',HabitDirection.Negative); r.habitInsights.recordObservation(h.id as unknown as string); const n = r.knowledgeSynthesizer.addNode(KnowledgeNodeType.Experience,'Context switching pattern','User switches between tasks frequently, reducing deep work time','behavior-analysis'); r.knowledgeSynthesizer.addEdge(n.id, n.id, KnowledgeEdgeType.RelatedTo, 0.5); expect(r.metrics.getCounter('habits_detected')).toBe(1); expect(r.metrics.getCounter('knowledge_nodes_created')).toBe(1); r.dispose(); });""")
    tests.append("""test('integration: conversation to goal', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); const interp = r.conversationInterpreter.interpret('I want to set a new goal for learning TypeScript'); expect(interp.intent).toBe(ConversationIntent.GoalSetting); const goal = r.goalPlanner.createGoal({title:'Learn TypeScript',level:GoalLevel.Goals,description:'From conversation'}); expect(r.metrics.getCounter('conversations_interpreted')).toBe(1); expect(r.metrics.getCounter('goals_created')).toBe(1); r.dispose(); });""")
    tests.append("""test('integration: full daily cycle', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); const morning = r.generateMorningBrief(); r.goalPlanner.createGoal({title:'Ship feature X',level:GoalLevel.Tasks}); r.goalPlanner.createGoal({title:'Write documentation',level:GoalLevel.Tasks}); r.constraintAnalyzer.detectConstraint('Missing API docs','Backend API not documented',ConstraintSeverity.Moderate); r.habitInsights.detectHabit('Deep work','2h focused sessions in morning',HabitDirection.Positive); r.knowledgeSynthesizer.addNode(KnowledgeNodeType.Note,'Sprint planning notes','Discussed priorities for the sprint','meeting'); r.conversationInterpreter.interpret('help me plan my week'); const priorities = r.priorityOptimizer.calculateAllPriorities(['g1','g2'], new Map() as any); r.valueAnalyzer.createAssessment(ValueDimension.UserValue,'Better planning','Sprint clarity','User',['Tasks completed'],'More predictable delivery',0.7); const evening = r.generateEveningReflection(); expect(r.metrics.getCounter('briefs_generated')).toBe(1); expect(r.metrics.getCounter('goals_created')).toBe(2); expect(r.metrics.getCounter('constraints_detected')).toBe(1); expect(r.metrics.getCounter('habits_detected')).toBe(1); expect(r.metrics.getCounter('knowledge_nodes_created')).toBe(1); expect(r.metrics.getCounter('conversations_interpreted')).toBe(1); expect(r.metrics.getCounter('reflections_generated')).toBe(1); expect(r.metrics.getCounter('value_assessments')).toBe(1); r.dispose(); });""")
    tests.append("""test('integration: priority calculation after goals', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); const g1 = r.goalPlanner.createGoal({title:'Urgent',level:GoalLevel.Tasks,priority:8}); const g2 = r.goalPlanner.createGoal({title:'Low priority',level:GoalLevel.Tasks,priority:2}); const f = new Map(); f.set(g1.id as unknown as string, {deadline:8,importance:8,urgency:8,energy:7,context:8,dependencies:8,risk:7,value:8}); f.set(g2.id as unknown as string, {deadline:2,importance:3,urgency:2,energy:5,context:3,dependencies:5,risk:4,value:3}); const scores = r.priorityOptimizer.calculateAllPriorities([g1.id as unknown as string, g2.id as unknown as string], f as any); expect(scores[0].totalScore).toBeGreaterThan(scores[1].totalScore); r.dispose(); });""")
    tests.append("""test('integration: knowledge graph from conversation', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); r.conversationInterpreter.interpret('We decided to use React for the frontend'); r.conversationInterpreter.interpret('The decision was based on team experience'); const n1 = r.knowledgeSynthesizer.addNode(KnowledgeNodeType.Conversation,'React decision','Team decided to use React','meeting'); const n2 = r.knowledgeSynthesizer.addNode(KnowledgeNodeType.Decision,'React choice','Chose React over Vue','meeting'); const n3 = r.knowledgeSynthesizer.addNode(KnowledgeNodeType.Conclusion,'Team experience drove the decision','React chosen because team already knows it','analysis'); r.knowledgeSynthesizer.addEdge(n1.id, n2.id, KnowledgeEdgeType.DecisionTo); r.knowledgeSynthesizer.addEdge(n2.id, n3.id, KnowledgeEdgeType.ConclusionTo); r.knowledgeSynthesizer.addEdge(n1.id, n3.id, KnowledgeEdgeType.Supports); const synth = r.knowledgeSynthesizer.getSynthesis(); expect(synth.totalNodes).toBe(3); expect(synth.totalEdges).toBe(3); r.dispose(); });""")
    tests.append("""test('integration: dashboard with all subsystems populated', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); r.generateMorningBrief(); const g = r.goalPlanner.createGoal({title:'Top goal',level:GoalLevel.Tasks}); const c = r.constraintAnalyzer.detectConstraint('C','d',ConstraintSeverity.Systemic); const rec = r.recommendationComposer.composeRecommendation('R','D',{why:'w',whyNow:'n',whatValue:'v',whyMainConstraint:'m'}); r.dashboard.addInsight('Insight 1','You are 20% more productive in mornings','productivity','system',0.85); r.dashboard.addInsight('Insight 2','Focus time has decreased this week','behavior','analysis',0.7); const db = r.dashboard.generateDashboard({{userId:'u1',todaySummary:'Good progress on main goal',topGoals:[g],nextActions:['Complete task A','Review decision B'],mainConstraint:c,mainRecommendation:rec,productivityIndex:78,developmentIndex:65}}); expect(db.topGoals.length).toBe(1); expect(db.mainConstraint).not.toBeNull(); expect(db.mainRecommendation).not.toBeNull(); expect(db.recentInsights.length).toBe(2); expect(db.productivityIndex).toBe(78); r.dispose(); });""")
    # Trace integration
    tests.append("""test('integration: trace spans for brief generation', async () => { const r = new PersonalIntelligencePackRuntime(C); await r.initialize(); const span = r.trace.startSpan('generateMorningBrief','DailyBriefGenerator'); r.generateMorningBrief(); r.trace.completeSpan(span.id as unknown as string); expect(r.trace.getSpansByOperation('generateMorningBrief').length).toBe(1); r.dispose(); });""")

    content = f"""import {{ describe, test, expect }} from 'vitest';
import {{ PersonalIntelligencePackRuntime }} from '../../core/personal-intelligence/personal-intelligence-pack-runtime.js';
import {{ GoalLevel, GoalStatus, ConstraintSeverity, ValueDimension, KnowledgeNodeType, KnowledgeEdgeType, ConversationIntent, HabitDirection }} from '../../core/personal-intelligence/types.js';

{mc()}
describe('Integration Tests', () => {{
{chr(10).join(tests)}
}});
"""
    w('integration.test.ts', content)

if __name__ == '__main__':
    os.makedirs(TEST_DIR, exist_ok=True)
    print(f"Generating batch 5 tests in {TEST_DIR}:")
    gen_integration()
    print("Done!")
