import os
T='/home/z/my-project/src/__tests__/desktop'
def w(p,c):
 os.makedirs(os.path.dirname(p),exist_ok=True)
 with open(p,'w') as f: f.write(c)
I="import { describe, it, expect, beforeEach } from 'vitest';\n"
LS=6
def gen(sub,cls,tests):
 lines=[I,'import { '+cls+'Runtime } from \'../../../desktop/'+sub+'/'+sub+'.js\';','']
 lines.append('describe(\''+cls+'Runtime\'', () => {')
 lines.append('  let runtime: '+cls+'Runtime;')
 lines.append('  beforeEach(async () => { runtime = new '+cls+'Runtime(); await runtime.initialize(); });')
 lines.append('')
 for d,code in tests:
 lines.append('    it(\''+d+'\', () => { '+code+' });')
 lines.append('});\n')
 w(T+'/'+sub+'/'+sub+'.test.ts', '\n'.join(lines))

gen('local-storage','LocalStorage',[
('set and get string','runtime.set("k", "v"); expect(runtime.get("k")).toBe("v")'),
('set and get number','runtime.set("k", 42); expect(runtime.get("k")).toBe(42)'),
('set and get boolean','runtime.set("k", true); expect(runtime.get("k")).toBe(true)'),
('set and get object','runtime.set("k", {a:1}); expect(runtime.get("k")).toEqual({a:1})'),
('set and get array','runtime.set("k", [1,2]); expect(runtime.get("k")).toEqual([1,2])'),
('set and get null','runtime.set("k", null); expect(runtime.get("k")).toBeNull()'),
('get missing undefined','expect(runtime.get("missing")).toBeUndefined()'),
('has true','runtime.set("x", 1); expect(runtime.has("x")).toBe(true)'),
('has false','expect(runtime.has("missing")).toBe(false)'),
('delete existing','runtime.set("d", 1); expect(runtime.delete("d")).toBe(true); expect(runtime.has("d")).toBe(false)'),
('delete missing','expect(runtime.delete("nope")).toBe(false)'),
('clear all','runtime.set("a", 1); runtime.set("b", 2); runtime.clear(); expect(runtime.size).toBe(0)'),
('size count','runtime.set("a", 1); runtime.set("b", 2); runtime.set("c", 3); expect(runtime.size).toBe(3)'),
('keys','runtime.set("a", 1); runtime.set("b", 2); expect(runtime.keys()).toHaveLength(2)'),
('entries','runtime.set("a", 1); runtime.set("b", 2); expect(runtime.entries()).toHaveLength(2)'),
('overwrite','runtime.set("k", 1); runtime.set("k", 2); expect(runtime.get("k")).toBe(2)'),
('empty key','runtime.set("", "empty"); expect(runtime.get("")).toBe("empty")'),
('100 entries','for(let i=0;i<100;i++) runtime.set("k"+i, i); expect(runtime.size).toBe(100)'),
('typed get','runtime.set("n", 42); const v: number|undefined = runtime.get<number>("n"); expect(v).toBe(42)'),
('has after delete','runtime.set("x", 1); runtime.delete("x"); expect(runtime.has("x")).toBe(false)'),
('get after delete','runtime.set("x", 1); runtime.delete("x"); expect(runtime.get("x")).toBeUndefined()'),
('same get twice','runtime.set("k", "v"); expect(runtime.get("k")).toBe("v"); expect(runtime.get("k")).toBe("v")'),
('zero value','runtime.set("k", 0); expect(runtime.get("k")).toBe(0)'),
('false value','runtime.set("k", false); expect(runtime.get("k")).toBe(false)'),
('empty string value','runtime.set("k", ""); expect(runtime.get("k")).toBe("")'),
('clear empty','runtime.clear(); expect(runtime.size).toBe(0)'),
('delete from empty','expect(runtime.delete("nope")).toBe(false)'),
('string stored as string','runtime.set("n", "42"); expect(runtime.get("n")).toBe("42")'),
('entries are pairs','runtime.set("a", 1); const e = runtime.entries()[0]; expect(e[0]).toBe("a"); expect(e[1]).toBe(1)'),
('keys order','runtime.set("b", 2); runtime.set("a", 1); expect(runtime.keys()[0]).toBe("b")'),
('has after clear','runtime.set("x", 1); runtime.clear(); expect(runtime.has("x")).toBe(false)'),
('never set','expect(runtime.get("never")).toBeUndefined()'),
('size zero','expect(runtime.size).toBe(0)'),
('set clear set','runtime.set("a", 1); runtime.clear(); runtime.set("b", 2); expect(runtime.size).toBe(1); expect(runtime.get("b")).toBe(2)'),
])
gen('search','SearchRuntime',[
('index and find','search.indexDocument("c", "1", {title:"Hello"}); expect(search.search("c", "hello")).toHaveLength(1)'),
('case insensitive','search.indexDocument("c", "1", {title:"HELLO"}); expect(search.search("c", "hello")).toHaveLength(1)'),
('no match','search.indexDocument("c", "1", {title:"Test"}); expect(search.search("c", "xyz")).toHaveLength(0)'),
('missing collection','expect(search.search("nope", "q")).toHaveLength(0)'),
('remove from index','search.indexDocument("c", "1", {title:"T"}); search.removeFromIndex("c", "1"); expect(search.search("c", "t")).toHaveLength(0)'),
('collection names','search.indexDocument("a", "1", {}); search.indexDocument("b", "2", {}); expect(search.getCollectionNames()).toHaveLength(2)'),
('collection size','search.indexDocument("c", "1", {}); search.indexDocument("c", "2", {}); expect(search.getCollectionSize("c")).toBe(2)'),
('missing size 0','expect(search.getCollectionSize("nope")).toBe(0)'),
('clear collection','search.indexDocument("c", "1", {}); search.clearCollection("c"); expect(search.search("c", "")).toHaveLength(0)'),
('clear all','search.indexDocument("a", "1", {}); search.indexDocument("b", "2", {}); search.clearAll(); expect(search.getCollectionNames()).toHaveLength(0)'),
('search across fields','search.indexDocument("c", "1", {title:"Hi", body:"World"}); expect(search.search("c", "world")).toHaveLength(1)'),
('empty query','search.indexDocument("c", "1", {title:"Test"}); expect(search.search("c", "")).toHaveLength(1)'),
('100 docs','for(let i=0;i<100;i++) search.indexDocument("c", String(i), {title:"D"+i}); expect(search.getCollectionSize("c")).toBe(100)'),
('independent collections','search.indexDocument("a", "1", {t:"A"}); search.indexDocument("b", "1", {t:"B"}); expect(search.search("a", "a")).toHaveLength(1); expect(search.search("b", "b")).toHaveLength(1)'),
('special chars','search.indexDocument("c", "1", {title:"<script>"}); expect(search.search("c", "<script>")).toHaveLength(1)'),
('overwrite','search.indexDocument("c", "1", {t:"Old"}); search.indexDocument("c", "1", {t:"New"}); expect(search.search("c", "new")).toHaveLength(1)'),
('numeric values','search.indexDocument("c", "1", {count:42}); expect(search.search("c", "42")).toHaveLength(1)'),
('partial match','search.indexDocument("c", "1", {title:"Application"}); expect(search.search("c", "app")).toHaveLength(1)'),
('multiple results','search.indexDocument("c", "1", {title:"Hello"}); search.indexDocument("c", "2", {title:"World Hello"}); expect(search.search("c", "hello")).toHaveLength(2)'),
('remove non-existent','search.removeFromIndex("nope", "1"); expect(search.getCollectionSize("c")).toBe(0)'),
('clear missing','search.clearCollection("nope"); expect(search.getCollectionNames()).toHaveLength(0)'),
('empty names','expect(search.getCollectionNames()).toHaveLength(0)'),
('search after clear','search.indexDocument("c", "1", {title:"T"}); search.clearCollection("c"); expect(search.search("c", "t")).toHaveLength(0)'),
('boolean searchable','search.indexDocument("c", "1", {active:true}); expect(search.search("c", "true")).toHaveLength(1)'),
('null searchable','search.indexDocument("c", "1", {val:null}); expect(search.search("c", "null")).toHaveLength(1)'),
])
gen('startup','StartupRuntime',[
('register step','startup.registerStep("s1", async()=>{}); expect(startup.getStepCount()).toBe(1)'),
('register multiple','startup.registerStep("s1", async()=>{}); startup.registerStep("s2", async()=>{}); expect(startup.getStepCount()).toBe(2)'),
('run sequence','let ran=false; startup.registerStep("t", async()=>{ran=true}); startup.runStartupSequence(); expect(ran).toBe(true)'),
('mark completed','startup.registerStep("a", async()=>{}); startup.registerStep("b", async()=>{}); startup.runStartupSequence(); expect(startup.isStepCompleted("a")).toBe(true)'),
('get completed','startup.registerStep("x", async()=>{}); startup.runStartupSequence(); expect(startup.getCompletedSteps()).toHaveLength(1)'),
('report duration','startup.registerStep("f", async()=>{}); startup.runStartupSequence(); expect(startup.getStartupDuration()).toBeGreaterThanOrEqual(0)'),
('async step','let v=0; startup.registerStep("a", async()=>{v=1}); startup.runStartupSequence(); expect(v).toBe(1)'),
('clear on rerun','startup.registerStep("s", async()=>{}); startup.runStartupSequence(); startup.runStartupSequence(); expect(startup.getCompletedSteps()).toHaveLength(1)'),
('steps in order','const o:string[]=[]; startup.registerStep("1", async()=>{o.push("1")}); startup.registerStep("2", async()=>{o.push("2")}); startup.runStartupSequence(); expect(o).toEqual(["1","2"])'),
('50 steps','for(let i=0;i<50;i++) startup.registerStep("s"+i, async()=>{}); startup.runStartupSequence(); expect(startup.getCompletedSteps()).toHaveLength(50)'),
('step error','startup.registerStep("e", async()=>{throw new Error("fail")}); try{await startup.runStartupSequence()}catch(e){expect(startup.getCompletedSteps()).toHaveLength(0)}'),
('completed unknown false','expect(startup.isStepCompleted("nope")).toBe(false)'),
('zero duration before','expect(startup.getStartupDuration()).toBe(0)'),
('empty steps initially','expect(startup.getStepCount()).toBe(0)'),
('empty completed initially','expect(startup.getCompletedSteps()).toHaveLength(0)'),
('step with delay','startup.registerStep("slow", async()=>{await new Promise(r=>setTimeout(r,1))}); startup.runStartupSequence(); expect(startup.getStartupDuration()).toBeGreaterThanOrEqual(0)'),
('rerun after error','let ok=false; startup.registerStep("s", async()=>{ok=true}); startup.runStartupSequence(); expect(ok).toBe(true)'),
('register returns void','expect(startup.registerStep("s", async()=>{})).toBeUndefined()'),
('count after register','startup.registerStep("s", async()=>{}); expect(startup.getStepCount()).toBe(1)'),
('completed after run','startup.registerStep("s", async()=>{}); startup.runStartupSequence(); expect(startup.isStepCompleted("s")).toBe(true)'),
('shutdown clears','startup.registerStep("s", async()=>{}); startup.shutdown(); expect(startup.getStepCount()).toBe(0)'),
])
gen('settings','SettingsRuntime',[
('set and get','settings.set("k", "v"); expect(settings.get("k")).toBe("v")'),
('get missing undefined','expect(settings.get("missing")).toBeUndefined()'),
('has true','settings.set("x", 1); expect(settings.has("x")).toBe(true)'),
('has false','expect(settings.has("y")).toBe(false)'),
('delete existing','settings.set("d", 1); expect(settings.delete("d")).toBe(true); expect(settings.has("d")).toBe(false)'),
('delete missing','expect(settings.delete("nope")).toBe(false)'),
('clear all','settings.set("a", 1); settings.clear(); expect(settings.getAll().size).toBe(0)'),
('register default','settings.registerDefault("theme", "dark"); expect(settings.get("theme")).toBe("dark")'),
('prefer set over default','settings.registerDefault("k", "def"); settings.set("k", "custom"); expect(settings.get("k")).toBe("custom")'),
('export settings','settings.set("a", 1); settings.set("b", 2); expect(settings.exportSettings()).toEqual({a:1,b:2})'),
('import settings','settings.importSettings({x:1, y:2}); expect(settings.get("x")).toBe(1)'),
('get defaults','settings.registerDefault("d1", 1); settings.registerDefault("d2", 2); expect(settings.getDefaults().size).toBe(2)'),
('typed get','settings.set("n", 42); expect(settings.get<number>("n")).toBe(42)'),
('overwrite','settings.set("k", 1); settings.set("k", 2); expect(settings.get("k")).toBe(2)'),
('object values','settings.set("o", {nested:{deep:true}}); expect(settings.get("o")).toEqual({nested:{deep:true}})'),
('array values','settings.set("a", [1,2,3]); expect(settings.get("a")).toEqual([1,2,3])'),
('import empty','settings.importSettings({}); expect(settings.getAll().size).toBe(0)'),
('100 settings','for(let i=0;i<100;i++) settings.set("k"+i, i); expect(settings.getAll().size).toBe(100)'),
('export empty','expect(settings.exportSettings()).toEqual({})'),
('delete default','settings.registerDefault("k", "v"); expect(settings.delete("k")).toBe(false); expect(settings.get("k")).toBe("v")'),
('has after delete','settings.set("k", 1); settings.delete("k"); expect(settings.has("k")).toBe(false)'),
('get after import','settings.importSettings({z:99}); expect(settings.get("z")).toBe(99)'),
('default not in getAll','settings.registerDefault("d", 1); expect(settings.getAll().size).toBe(0)'),
('number type','settings.set("n", 3.14); expect(settings.get("n")).toBe(3.14)'),
('boolean type','settings.set("b", false); expect(settings.get("b")).toBe(false)'),
('clear no remove defaults','settings.registerDefault("d", 1); settings.set("x", 2); settings.clear(); expect(settings.get("d")).toBe("1")'),
('multiple defaults','settings.registerDefault("a", 1); settings.registerDefault("b", 2); expect(settings.get("a")).toBe(1); expect(settings.get("b")).toBe(2)'),
])
gen('diagnostics','DiagnosticsRuntime',[
('register health check','diag.registerHealthCheck("ok", async()=>({healthy:true})); expect(diag.getHealthCheckCount()).toBe(1)'),
('run health checks','diag.registerHealthCheck("ok", async()=>({healthy:true})); diag.registerHealthCheck("fail", async()=>({healthy:false, message:"bad"})); const r=await diag.runHealthChecks(); expect(r["ok"].healthy).toBe(true); expect(r["fail"].healthy).toBe(false)'),
('record metric','diag.recordMetric("cpu", 42); expect(diag.getMetric("cpu")).toBe(42)'),
('missing metric','expect(diag.getMetric("nope")).toBeUndefined()'),
('get all metrics','diag.recordMetric("a", 1); diag.recordMetric("b", 2); expect(diag.getAllMetrics().size).toBe(2)'),
('log messages','diag.log("info", "test"); diag.log("error", "fail"); expect(diag.getLogs()).toHaveLength(2)'),
('clear logs','diag.log("info", "x"); diag.clearLogs(); expect(diag.getLogs()).toHaveLength(0)'),
('overwrite metric','diag.recordMetric("m", 1); diag.recordMetric("m", 2); expect(diag.getMetric("m")).toBe(2)'),
('50 checks','for(let i=0;i<50;i++) diag.registerHealthCheck("hc"+i, async()=>({healthy:true})); expect(diag.getHealthCheckCount()).toBe(50)'),
('100 metrics','for(let i=0;i<100;i++) diag.recordMetric("m"+i, i); expect(diag.getAllMetrics().size).toBe(100)'),
('100 logs','for(let i=0;i<100;i++) diag.log("info", "msg"+i); expect(diag.getLogs()).toHaveLength(100)'),
('log timestamp','diag.log("info", "t"); expect(diag.getLogs()[0]?.timestamp).toBeDefined()'),
('log level','diag.log("warn", "w"); expect(diag.getLogs()[0]?.level).toBe("warn")'),
('async check','diag.registerHealthCheck("slow", async()=>{await Promise.resolve(); return {healthy:true}}); const r=await diag.runHealthChecks(); expect(r["slow"].healthy).toBe(true)'),
('empty results','const r=await diag.runHealthChecks(); expect(Object.keys(r)).toHaveLength(0)'),
('zero check count','expect(diag.getHealthCheckCount()).toBe(0)'),
('empty logs','expect(diag.getLogs()).toHaveLength(0)'),
('check message','diag.registerHealthCheck("m", async()=>({healthy:false, message:"detail"})); const r=await diag.runHealthChecks(); expect(r["m"].message).toBe("detail")'),
('error level','diag.log("error", "e"); const l=diag.getLogs()[0]; expect(l?.level).toBe("error"); expect(l?.message).toBe("e")'),
('metric zero','diag.recordMetric("z", 0); expect(diag.getMetric("z")).toBe(0)'),
('metric negative','diag.recordMetric("n", -1); expect(diag.getMetric("n")).toBe(-1)'),
('clear metrics on shutdown','diag.recordMetric("m", 1); diag.shutdown(); expect(diag.getAllMetrics().size).toBe(0)'),
('clear logs on shutdown','diag.log("x", "y"); diag.shutdown(); expect(diag.getLogs()).toHaveLength(0)'),
])
gen('crash-recovery','CrashRecoveryRuntime',[
('save snapshot','crash.saveSnapshot("s1", {x:1}); expect(crash.hasSnapshot("s1")).toBe(true)'),
('get snapshot','crash.saveSnapshot("s1", {data:"test"}); expect(crash.getSnapshot("s1")?.data).toBe("test")'),
('missing snapshot','expect(crash.getSnapshot("nope")).toBeUndefined()'),
('delete snapshot','crash.saveSnapshot("s1", {}); expect(crash.deleteSnapshot("s1")).toBe(true); expect(crash.hasSnapshot("s1")).toBe(false)'),
('delete missing','expect(crash.deleteSnapshot("nope")).toBe(false)'),
('snapshot ids','crash.saveSnapshot("a", {}); crash.saveSnapshot("b", {}); expect(crash.getSnapshotIds()).toHaveLength(2)'),
('record crash','crash.recordCrash("OOM", {mem:0}); expect(crash.getCrashCount()).toBe(1)'),
('get last crash','crash.recordCrash("err", {}); expect(crash.getLastCrash()?.reason).toBe("err")'),
('no last crash','expect(crash.getLastCrash()).toBeUndefined()'),
('track recovered','crash.setCrashRecovered(true); expect(crash.lastCrashRecovered).toBe(true); crash.setCrashRecovered(false); expect(crash.lastCrashRecovered).toBe(false)'),
('clear crash log','crash.recordCrash("a", {}); crash.clearCrashLog(); expect(crash.getCrashCount()).toBe(0)'),
('clear snapshots','crash.saveSnapshot("a", {}); crash.clearSnapshots(); expect(crash.getSnapshotIds()).toHaveLength(0)'),
('multiple crashes','crash.recordCrash("a", {}); crash.recordCrash("b", {}); expect(crash.getCrashCount()).toBe(2)'),
('latest crash','crash.recordCrash("first", {}); crash.recordCrash("second", {}); expect(crash.getLastCrash()?.reason).toBe("second")'),
('crash timestamp','crash.recordCrash("t", {}); expect(crash.getLastCrash()?.timestamp).toBeDefined()'),
('crash state','crash.recordCrash("s", {key:"val"}); expect(crash.getLastCrash()?.state).toEqual({key:"val"})'),
('snapshot savedAt','crash.saveSnapshot("s", {}); expect((crash.getSnapshot("s") as any)?.savedAt).toBeDefined()'),
('100 snapshots','for(let i=0;i<100;i++) crash.saveSnapshot("s"+i, {i}); expect(crash.getSnapshotIds()).toHaveLength(100)'),
('overwrite snapshot','crash.saveSnapshot("s", {v:1}); crash.saveSnapshot("s", {v:2}); expect(crash.getSnapshot("s")?.v).toBe(2)'),
('has false','expect(crash.hasSnapshot("nope")).toBe(false)'),
('empty log','expect(crash.getCrashCount()).toBe(0)'),
('empty ids','expect(crash.getSnapshotIds()).toHaveLength(0)'),
('complex state','crash.saveSnapshot("s", {windows:[1,2,3], active:"home"}); const s=crash.getSnapshot("s"); expect((s as any)?.windows).toEqual([1,2,3])'),
])
gen('notification','NotificationRuntime',[
('create','const id=notif.create("T", "B"); expect(id).toBeDefined(); expect(notif.getUnreadCount()).toBe(1)'),
('with type','const id=notif.create("T", "B", "error"); expect(notif.getById(id)?.type).toBe("error")'),
('with priority','const id=notif.create("T", "B", "info", 10); expect(notif.getById(id)?.priority).toBe(10)'),
('default type','const id=notif.create("T", "B"); expect(notif.getById(id)?.type).toBe("info")'),
('default priority','const id=notif.create("T", "B"); expect(notif.getById(id)?.priority).toBe(0)'),
('mark read','const id=notif.create("T", "B"); notif.markRead(id); expect(notif.getUnreadCount()).toBe(0)'),
('mark all read','notif.create("T1", "B1"); notif.create("T2", "B2"); notif.markAllRead(); expect(notif.getUnreadCount()).toBe(0)'),
('get all','notif.create("A", "B"); notif.create("C", "D"); expect(notif.getAll()).toHaveLength(2)'),
('get by id','const id=notif.create("T", "B"); expect(notif.getById(id)?.title).toBe("T")'),
('get missing','expect(notif.getById("nope")).toBeUndefined()'),
('delete','const id=notif.create("T", "B"); notif.delete(id); expect(notif.getAll()).toHaveLength(0)'),
('clear all','notif.create("T", "B"); notif.clear(); expect(notif.getAll()).toHaveLength(0)'),
('no double count','const id=notif.create("T", "B"); notif.markRead(id); notif.markRead(id); expect(notif.getUnreadCount()).toBe(0)'),
('100 notifications','for(let i=0;i<100;i++) notif.create("T"+i, "B"+i); expect(notif.getAll()).toHaveLength(100)'),
('delete unread decr','const id=notif.create("T", "B"); notif.delete(id); expect(notif.getUnreadCount()).toBe(0)'),
('delete read no decr','const id=notif.create("T", "B"); notif.markRead(id); notif.delete(id); expect(notif.getUnreadCount()).toBe(0)'),
('has createdAt','const id=notif.create("T", "B"); expect(notif.getById(id)?.createdAt).toBeDefined()'),
('mark read then create','notif.create("T", "B"); notif.markAllRead(); notif.create("T2", "B2"); expect(notif.getUnreadCount()).toBe(1)'),
('delete non-existent','notif.delete("nope"); expect(notif.getAll()).toHaveLength(0)'),
('clear no items','notif.clear(); expect(notif.getUnreadCount()).toBe(0)'),
('getById after clear','const id=notif.create("T", "B"); notif.clear(); expect(notif.getById(id)).toBeUndefined()'),
('unique ids','const id1=notif.create("T", "B"); const id2=notif.create("T", "B"); expect(id1).not.toBe(id2)'),
('body','const id=notif.create("Title", "Body text"); expect(notif.getById(id)?.body).toBe("Body text")'),
('default expiresAt null','const id=notif.create("T", "B"); expect(notif.getById(id)?.expiresAt).toBeNull()'),
('markRead idempotent','const id=notif.create("T", "B"); notif.markRead(id); expect(notif.getUnreadCount()).toBe(0); expect(notif.getUnreadCount()).toBe(0)'),
('unread after clear','notif.create("T", "B"); notif.clear(); expect(notif.getUnreadCount()).toBe(0)'),
('multiple markAllRead','notif.create("T", "B"); notif.markAllRead(); notif.markAllRead(); expect(notif.getUnreadCount()).toBe(0)'),
])
gen('command-palette','CommandPaletteRuntime',[
('register','palette.register("c1", "Test", ()=>{}); expect(palette.getCount()).toBe(1)'),
('with options','palette.register("c2", "Test2", ()=>{}, {description:"desc", category:"cat"}); const c=palette.getAll()[0]; expect(c?.description).toBe("desc"); expect(c?.category).toBe("cat")'),
('with keybinding','palette.register("c3", "Test3", ()=>{}, {keybinding:"Ctrl+K"}); expect(palette.getAll()[0]?.keybinding).toBe("Ctrl+K")'),
('unregister','palette.register("c4", "T4", ()=>{}); expect(palette.unregister("c4")).toBe(true)'),
('execute sync','let ex=false; palette.register("c5", "Run", ()=>{ex=true}); palette.execute("c5"); expect(ex).toBe(true)'),
('execute async','let v=0; palette.register("c6", "Async", async()=>{v=1}); palette.execute("c6"); expect(v).toBe(1)'),
('search by label','palette.register("find-me", "Find Me", ()=>{}, {description:"searchable"}); expect(palette.search("find")).toHaveLength(1)'),
('search by desc','palette.register("c7", "Label", ()=>{}, {description:"hidden gem"}); expect(palette.search("hidden")).toHaveLength(1)'),
('no match','palette.register("c8", "Test", ()=>{}); expect(palette.search("xyz")).toHaveLength(0)'),
('disable','palette.register("c9", "Test", ()=>{}); palette.setEnabled("c9", false); expect(palette.search("test")).toHaveLength(0)'),
('re-enable','palette.register("c10", "T", ()=>{}); palette.setEnabled("c10", false); palette.setEnabled("c10", true); expect(palette.search("t")).toHaveLength(1)'),
('execute missing throws','expect(palette.execute("nope")).rejects.toThrow()'),
('execute disabled throws','palette.register("c11", "T", ()=>{}); palette.setEnabled("c11", false); expect(palette.execute("c11")).rejects.toThrow()'),
('track history','palette.register("c12", "H", ()=>{}); palette.execute("c12"); expect(palette.getHistory()).toHaveLength(1)'),
('get all','palette.register("a", "A", ()=>{}); palette.register("b", "B", ()=>{}); expect(palette.getAll()).toHaveLength(2)'),
('default category','palette.register("c13", "T", ()=>{}); expect(palette.getAll()[0]?.category).toBe("General")'),
('default keybinding null','palette.register("c14", "T", ()=>{}); expect(palette.getAll()[0]?.keybinding).toBeNull()'),
('default enabled','palette.register("c15", "T", ()=>{}); expect(palette.getAll()[0]?.enabled).toBe(true)'),
('100 commands','for(let i=0;i<100;i++) palette.register("c"+i, "Cmd"+i, ()=>{}); expect(palette.getCount()).toBe(100)'),
('unregister missing','expect(palette.unregister("nope")).toBe(false)'),
('case insensitive','palette.register("c16", "UPPER", ()=>{}); expect(palette.search("upper")).toHaveLength(1)'),
('result has id','palette.register("c17", "Test", ()=>{}); expect(palette.search("test")[0]?.id).toBe("c17")'),
('history timestamp','palette.register("c18", "H", ()=>{}); palette.execute("c18"); expect(palette.getHistory()[0]?.timestamp).toBeDefined()'),
('history query','palette.register("c19", "H", ()=>{}); palette.execute("c19"); expect(palette.getHistory()[0]?.query).toBe("H")'),
('setEnabled no error','palette.setEnabled("nope", false); expect(true).toBe(true)'),
('getAll includes disabled','palette.register("a", "A", ()=>{}); palette.register("b", "B", ()=>{}); palette.setEnabled("a", false); expect(palette.getAll()).toHaveLength(2); expect(palette.search("a")).toHaveLength(1)'),
('empty query','palette.register("x", "X", ()=>{}); const r=palette.search(""); expect(r.length).toBeGreaterThan(0)'),
('unregister then search','palette.register("c20", "Find", ()=>{}); palette.unregister("c20"); expect(palette.search("find")).toHaveLength(0)'),
('execute adds history','palette.register("c21", "T", ()=>{}); palette.execute("c21"); palette.execute("c21"); expect(palette.getHistory()).toHaveLength(2)'),
])

print('Done: ' + str(len(tests_data)) + ' test cases across ' + str(len(tests_data)) + ' subsystems')
